import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { publicApi } from '@/lib/api';
import { ShareProfile } from '@/components/rivera/share-profile';
type Business={slug:string;businessName:string;shortDescription?:string;description:string;industry?:{name:string};website?:string;countryCode:string;city:string;logoUrl?:string;coverImageUrl?:string;yearEstablished?:number;employeeSize?:string;verificationStatus:string};
async function business(slug:string){return publicApi<Business>(`/businesses/${encodeURIComponent(slug)}`)}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const profile=await business(slug);return profile?{title:`${profile.businessName} — ${profile.industry?.name??'Business'} | Rivera`,description:profile.shortDescription??profile.description.slice(0,150),alternates:{canonical:`/businesses/${profile.slug}`}}:{title:'Business not found | Rivera'}}
export default async function BusinessPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const profile=await business(slug);if(!profile)notFound();return <main className="public-profile"><nav><Link href="/" className="brand"><span className="brand-mark">R.</span>rivera</Link><Link href="/creators">Find creators</Link></nav><div className="profile-cover business-cover" style={profile.coverImageUrl?{backgroundImage:`url(${profile.coverImageUrl})`}:undefined}/><header className="public-identity"><div className="public-avatar">{profile.logoUrl?<Image unoptimized width={150} height={150} src={profile.logoUrl} alt={`${profile.businessName} logo`}/>:profile.businessName.slice(0,1)}</div><div><p className="creator-location">{profile.city}, {profile.countryCode}</p><h1>{profile.businessName}{profile.verificationStatus==='VERIFIED'&&<span title="Verified by Rivera"> ✓</span>}</h1><h2>{profile.industry?.name}</h2><p>{profile.shortDescription}</p></div><ShareProfile title={`${profile.businessName} on Rivera`}/></header><div className="public-profile-grid"><section><p className="eyebrow">ABOUT THE BUSINESS</p><p className="profile-bio">{profile.description}</p>{profile.website&&<a href={profile.website} target="_blank" rel="noopener noreferrer">Visit website ↗</a>}</section><aside>{profile.yearEstablished&&<div className="stat-card"><strong>{profile.yearEstablished}</strong><span>Year established</span></div>}{profile.employeeSize&&<div className="stat-card"><strong>{profile.employeeSize.replaceAll('_',' ')}</strong><span>Company size</span></div>}<p>Private contact information is shared only through future authorized campaign workflows.</p></aside></div></main>}
