import type { Metadata } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import { notFound } from 'next/navigation';
import { publicApi } from '@/lib/api';
import { ShareProfile } from '@/components/rivera/share-profile';
type Business={slug:string;businessName:string;shortDescription?:string;description:string;industry?:{name:string};website?:string;countryCode:string;city:string;logoUrl?:string;coverImageUrl?:string;yearEstablished?:number;employeeSize?:string;verificationStatus:string};
type Reviews={averageRating:string;ratingCount:number;items:{id:string;rating:number;comment?:string;createdAt:string;reviewer:{name:string};campaign:{title:string}}[]};
const business=(slug:string)=>publicApi<Business>(`/businesses/${encodeURIComponent(slug)}`);
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=await business(slug);return p?{title:`${p.businessName} — ${p.industry?.name??'Business'} | Rivera`,description:p.shortDescription??p.description.slice(0,150),alternates:{canonical:`/businesses/${p.slug}`}}:{title:'Business not found | Rivera'}}
export default async function BusinessPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [p,reviews]=await Promise.all([business(slug),publicApi<Reviews>(`/businesses/${encodeURIComponent(slug)}/reviews`)]);if(!p)notFound();return <main className="public-profile"><nav><Link href="/" className="brand"><span className="brand-mark">R.</span>rivera</Link><Link href="/creators">Find creators</Link></nav><div className="profile-cover business-cover" style={p.coverImageUrl?{backgroundImage:`url(${p.coverImageUrl})`}:undefined}/><header className="public-identity"><div className="public-avatar">{p.logoUrl?<Image unoptimized width={150} height={150} src={p.logoUrl} alt={`${p.businessName} logo`}/>:p.businessName[0]}</div><div><p className="creator-location">{p.city}, {p.countryCode}</p><h1>{p.businessName}{p.verificationStatus==='VERIFIED'&&<span title="Verified by Rivera"> ✓</span>}</h1><h2>{p.industry?.name}</h2><p>{p.shortDescription}</p><p aria-label={`${reviews?.averageRating??0} out of 5 stars`}>★ {reviews?.averageRating??'0.00'} · {reviews?.ratingCount??0} verified collaboration reviews</p></div><ShareProfile title={`${p.businessName} on Rivera`}/></header><div className="public-profile-grid"><div><section><p className="eyebrow">ABOUT THE BUSINESS</p><p className="profile-bio">{p.description}</p>{p.website&&<a href={p.website} target="_blank" rel="noopener noreferrer">Visit website ↗</a>}</section><section><p className="eyebrow">REVIEWS</p>{reviews?.items.length?reviews.items.map(x=><article key={x.id} className="stat-card"><strong>{'★'.repeat(x.rating)}{'☆'.repeat(5-x.rating)}</strong><p>{x.comment||'Rating submitted without a comment.'}</p><small>{x.reviewer.name} · {x.campaign.title} · {new Date(x.createdAt).toLocaleDateString()}</small></article>):<p>No completed-collaboration reviews yet.</p>}</section></div><aside>{p.yearEstablished&&<div className="stat-card"><strong>{p.yearEstablished}</strong><span>Year established</span></div>}{p.employeeSize&&<div className="stat-card"><strong>{p.employeeSize.replaceAll('_',' ')}</strong><span>Company size</span></div>}<p>Private contact information is shared only with authorized campaign participants.</p></aside></div></main>}
