/* eslint-disable @typescript-eslint/no-explicit-any */
import { HttpStatus, Inject, Injectable } from '@nestjs/common';
import { ApplicationStatus, Prisma } from '@prisma/client';
import { ApiException } from '../common/api-error';
import { PrismaService } from '../common/prisma.service';
import { MailService } from '../auth/mail.service';
import { ApplicationQueryDto, CreditGrantDto, FeeRuleDto, ProposalDto, RefundDto } from './dto';
import { CampaignEligibilityService } from './eligibility.service';
import { ApplicationFeeService } from './fee.service';
import { PAYMENT_PROVIDER, PaymentProviderAdapter, ProviderPayment, VerifiedWebhook } from './payment.provider';

const creatorProfileInclude = { categories:{include:{category:true}},socialAccounts:{orderBy:{followers:'desc' as const}},portfolio:{where:{published:true},orderBy:{sortOrder:'asc' as const}},languages:true,contentTypes:{include:{contentType:true}} };
const safeBusiness = { id:true,name:true,slug:true,logoUrl:true,shortDescription:true,verificationStatus:true,country:true,city:true };
const campaignForApplication = { business:{select:safeBusiness},categories:{include:{category:true}},platforms:true,languages:true,deliverables:{include:{contentType:true},orderBy:{sortOrder:'asc' as const}},creatorLocations:true,attachments:true };
const applicationInclude = { campaign:{include:campaignForApplication},creator:{include:creatorProfileInclude},payments:{orderBy:{createdAt:'desc' as const}},applicationFeeRule:true };

@Injectable()
export class ApplicationsService {
  constructor(private db:PrismaService,private eligibility:CampaignEligibilityService,private fees:ApplicationFeeService,@Inject(PAYMENT_PROVIDER) private provider:PaymentProviderAdapter,private mail:MailService){}
  private fail(status:HttpStatus,code:string,message:string):never{throw new ApiException(status,code,message);}
  private publicCampaign(c:any){return{id:c.id,slug:c.slug,title:c.title,shortDescription:c.shortDescription,campaignObjective:c.campaignObjective,locationType:c.locationType,campaignCountryCode:c.campaignCountryCode,campaignCity:c.campaignCity,campaignRegion:c.campaignRegion,creatorLocations:c.creatorLocations,budgetMinMinor:c.budgetVisibility==='PUBLIC'?c.budgetMinMinor:null,budgetMaxMinor:c.budgetVisibility==='PUBLIC'?c.budgetMaxMinor:null,budgetVisibility:c.budgetVisibility,currencyCode:c.currencyCode,creatorSlots:c.creatorSlots,applicationDeadline:c.applicationDeadline,campaignStartDate:c.campaignStartDate,campaignEndDate:c.campaignEndDate,status:c.status,visibility:c.visibility,verifiedCreatorsOnly:c.verifiedCreatorsOnly,business:c.business,categories:c.categories.map((x:any)=>({...x.category,isPrimary:x.isPrimary})),platforms:c.platforms,languages:c.languages,deliverables:c.deliverables.map((x:any)=>({title:x.title,quantity:x.quantity,platform:x.platform,contentType:x.contentType?{name:x.contentType.name,slug:x.contentType.slug}:null})),attachments:c.attachments.filter((x:any)=>x.visibility==='PUBLIC').map((x:any)=>({name:x.name,fileUrl:x.fileUrl,mimeType:x.mimeType,fileSize:x.fileSize}))};}
  private unlockedCampaign(c:any){return{...this.publicCampaign(c),fullDescription:c.fullDescription,productOrServiceName:c.productOrServiceName,productOrServiceDescription:c.productOrServiceDescription,productUrl:c.productUrl,targetAudience:c.targetAudience,expectedOutcomes:c.expectedOutcomes,usageRights:c.usageRights,usageRightsNotes:c.usageRightsNotes,productProvided:c.productProvided,travelExpensesCovered:c.travelExpensesCovered,specialInstructions:c.specialInstructions,deliverables:c.deliverables,attachments:c.attachments.filter((x:any)=>x.visibility!=='OWNER_ONLY').map((x:any)=>({name:x.name,fileUrl:x.fileUrl,mimeType:x.mimeType,fileSize:x.fileSize,visibility:x.visibility}))};}
  private safeCreator(c:any){return{id:c.id,slug:c.slug,displayName:c.displayName,headline:c.headline,bio:c.bio,country:c.country,city:c.city,profileImageUrl:c.profileImageUrl,coverImageUrl:c.coverImageUrl,verificationStatus:c.verificationStatus,categories:c.categories.map((x:any)=>({...x.category,isPrimary:x.isPrimary})),socialAccounts:c.socialAccounts,portfolio:c.portfolio,languages:c.languages,contentTypes:c.contentTypes.map((x:any)=>x.contentType),combinedFollowers:c.socialAccounts.reduce((sum:number,x:any)=>sum+x.followers,0)};}
  private ownDto(a:any){const unlocked=['SUBMITTED','VIEWED','WITHDRAWN'].includes(a.status)&&(a.paymentStatus==='PAID'||a.paymentStatus==='NOT_REQUIRED');return{id:a.id,status:a.status,paymentStatus:a.paymentStatus,proposedAmountMinor:a.proposedAmountMinor,proposedCurrencyCode:a.proposedCurrencyCode,pitch:a.pitch,proposedDeliverables:a.proposedDeliverables,estimatedDeliveryDays:a.estimatedDeliveryDays,additionalNotes:a.additionalNotes,applicationFeeMinor:a.applicationFeeMinor,applicationFeeCurrencyCode:a.applicationFeeCurrencyCode,usedFreeCredit:a.usedFreeCredit,submittedAt:a.submittedAt,viewedAt:a.viewedAt,withdrawnAt:a.withdrawnAt,createdAt:a.createdAt,updatedAt:a.updatedAt,campaign:unlocked?this.unlockedCampaign(a.campaign):this.publicCampaign(a.campaign),payments:a.payments?.map((p:any)=>({id:p.id,amountMinor:p.amountMinor,currencyCode:p.currencyCode,status:p.status,paidAt:p.paidAt,refundedAt:p.refundedAt,reference:this.shortRef(p.providerPaymentId??p.providerCheckoutSessionId)}))??[]};}
  private businessDto(a:any){return{id:a.id,status:a.status,proposedAmountMinor:a.proposedAmountMinor,proposedCurrencyCode:a.proposedCurrencyCode,pitch:a.pitch,proposedDeliverables:a.proposedDeliverables,estimatedDeliveryDays:a.estimatedDeliveryDays,additionalNotes:a.additionalNotes,submittedAt:a.submittedAt,viewedAt:a.viewedAt,withdrawnAt:a.withdrawnAt,creator:this.safeCreator(a.creator)};}
  private shortRef(value?:string|null){return value?`${value.slice(0,8)}…${value.slice(-4)}`:null;}
  private audit(tx:Prisma.TransactionClient,applicationId:string,actorUserId:string,action:string,metadata?:Prisma.InputJsonValue){return tx.applicationAuditLog.create({data:{applicationId,actorUserId,action,metadata}});}
  private async creator(userId:string){const creator=await this.db.creatorProfile.findUnique({where:{userId}});if(!creator)this.fail(HttpStatus.BAD_REQUEST,'CREATOR_PROFILE_INCOMPLETE','Complete your Creator profile first.');return creator;}
  private async owned(userId:string,id:string){const creator=await this.creator(userId);const app=await this.db.campaignApplication.findFirst({where:{id,creatorId:creator.id},include:applicationInclude});if(!app)this.fail(HttpStatus.NOT_FOUND,'APPLICATION_NOT_FOUND','Application not found.');return app;}

  async eligibilityPreview(userId:string,campaignId:string){const result=await this.eligibility.inspect(userId,campaignId);const existing=await this.db.campaignApplication.findUnique({where:{campaignId_creatorId:{campaignId,creatorId:result.creator.id}}});return{canApply:result.canApply&&!existing,blockingReasons:existing?['APPLICATION_ALREADY_EXISTS']:result.blockingReasons,warnings:result.advisoryWarnings,existingApplicationId:existing?.id??null};}
  async feePreview(userId:string,campaignId:string){const result=await this.eligibility.inspect(userId,campaignId);const fee=await this.fees.resolve(campaignId,result.creator.id);return{amountMinor:fee.amountMinor,currencyCode:fee.currencyCode,freeCreditAvailable:result.creator.freeApplicationCredits>0,freeApplicationCredits:result.creator.freeApplicationCredits,canApply:result.canApply,blockingReasons:result.blockingReasons,warnings:result.advisoryWarnings};}
  async createDraft(userId:string,campaignId:string,dto:ProposalDto){const {creator,campaign}=await this.eligibility.require(userId,campaignId);if(dto.proposedCurrencyCode.toUpperCase()!==campaign.currencyCode)this.fail(HttpStatus.BAD_REQUEST,'INVALID_PROPOSAL_CURRENCY',`Proposal currency must be ${campaign.currencyCode}.`);try{const app=await this.db.campaignApplication.create({data:{campaignId,creatorId:creator.id,proposedAmountMinor:dto.proposedAmountMinor,proposedCurrencyCode:campaign.currencyCode,pitch:dto.pitch,proposedDeliverables:dto.proposedDeliverables,estimatedDeliveryDays:dto.estimatedDeliveryDays,additionalNotes:dto.additionalNotes,paymentStatus:'PENDING'},include:applicationInclude});await this.db.applicationAuditLog.create({data:{applicationId:app.id,actorUserId:userId,action:'APPLICATION_STARTED'}});return this.ownDto(app);}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')this.fail(HttpStatus.CONFLICT,'APPLICATION_ALREADY_EXISTS','You already have a proposal for this Campaign.');throw error;}}
  async update(userId:string,id:string,dto:ProposalDto){const app=await this.owned(userId,id);if(!['DRAFT'].includes(app.status))this.fail(HttpStatus.CONFLICT,'APPLICATION_ALREADY_SUBMITTED','Submitted proposals cannot be edited.');if(dto.proposedCurrencyCode.toUpperCase()!==app.campaign.currencyCode)this.fail(HttpStatus.BAD_REQUEST,'INVALID_PROPOSAL_CURRENCY',`Proposal currency must be ${app.campaign.currencyCode}.`);const updated=await this.db.campaignApplication.update({where:{id},data:{proposedAmountMinor:dto.proposedAmountMinor,proposedCurrencyCode:app.campaign.currencyCode,pitch:dto.pitch,proposedDeliverables:dto.proposedDeliverables,estimatedDeliveryDays:dto.estimatedDeliveryDays,additionalNotes:dto.additionalNotes},include:applicationInclude});return this.ownDto(updated);}
  async review(userId:string,id:string){const app=await this.owned(userId,id);if(app.status!=='DRAFT')this.fail(HttpStatus.CONFLICT,'INVALID_APPLICATION_STATE','Only draft proposals can be reviewed.');const check=await this.eligibility.require(userId,app.campaignId);const fee=await this.fees.resolve(app.campaignId,app.creatorId);const reviewed=await this.db.campaignApplication.update({where:{id},data:{applicationFeeMinor:fee.amountMinor,applicationFeeCurrencyCode:fee.currencyCode,applicationFeeRuleId:fee.ruleId},include:applicationInclude});await this.db.applicationAuditLog.create({data:{applicationId:id,actorUserId:userId,action:'APPLICATION_REVIEWED'}});return{application:this.ownDto(reviewed),fee:{amountMinor:fee.amountMinor,currencyCode:fee.currencyCode},freeApplicationCredits:check.creator.freeApplicationCredits,warnings:check.advisoryWarnings,outsideBudget:(app.campaign.budgetMinMinor!=null&&app.proposedAmountMinor<app.campaign.budgetMinMinor)||(app.campaign.budgetMaxMinor!=null&&app.proposedAmountMinor>app.campaign.budgetMaxMinor)};}
  private async submitWithoutPayment(userId:string,id:string,useCredit:boolean){const app=await this.owned(userId,id);if(app.status!=='DRAFT')this.fail(HttpStatus.CONFLICT,'APPLICATION_ALREADY_SUBMITTED','This proposal has already entered submission.');await this.eligibility.require(userId,app.campaignId);const fee=await this.fees.resolve(app.campaignId,app.creatorId);if(!useCredit&&fee.amountMinor>0)this.fail(HttpStatus.PAYMENT_REQUIRED,'PAYMENT_REQUIRED','The Rivera Application Fee must be paid before submission.');const submitted=await this.db.$transaction(async tx=>{if(useCredit){const changed=await tx.creatorProfile.updateMany({where:{id:app.creatorId,freeApplicationCredits:{gt:0}},data:{freeApplicationCredits:{decrement:1}}});if(changed.count!==1)this.fail(HttpStatus.CONFLICT,'INSUFFICIENT_FREE_CREDITS','You do not have a free application credit available.');const creator=await tx.creatorProfile.findUniqueOrThrow({where:{id:app.creatorId}});await tx.applicationCreditTransaction.create({data:{creatorId:app.creatorId,type:'USE',quantity:-1,balanceAfter:creator.freeApplicationCredits,reason:`Application to ${app.campaign.title}`,referenceId:id}});}
      const updated=await tx.campaignApplication.update({where:{id},data:{status:'SUBMITTED',paymentStatus:'NOT_REQUIRED',applicationFeeMinor:fee.amountMinor,applicationFeeCurrencyCode:fee.currencyCode,applicationFeeRuleId:fee.ruleId,usedFreeCredit:useCredit,submittedAt:new Date()},include:applicationInclude});
      await this.audit(tx,id,userId,'APPLICATION_SUBMITTED',{method:useCredit?'FREE_CREDIT':'ZERO_FEE'});if(useCredit)await this.audit(tx,id,userId,'FREE_APPLICATION_CREDIT_USED');await tx.notification.createMany({data:[{userId,creatorId:app.creatorId,applicationId:id,type:'PROPOSAL_SUBMITTED',title:'Proposal submitted',body:`Your proposal for ${app.campaign.title} was submitted successfully.`},{userId:app.campaign.businessId?await this.businessUserId(tx,app.campaign.businessId):userId,businessId:app.campaign.businessId,applicationId:id,type:'NEW_PROPOSAL',title:'New proposal received',body:`A Creator submitted a proposal for ${app.campaign.title}.`} ]});return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
    void this.sendSubmissionEmails(submitted);return this.ownDto(submitted);}
  async useCredit(userId:string,id:string){return this.submitWithoutPayment(userId,id,true);}
  private businessUserId(tx:Prisma.TransactionClient,businessId:string){return tx.businessProfile.findUniqueOrThrow({where:{id:businessId},select:{userId:true}}).then(x=>x.userId);}

  async checkout(userId:string,id:string){const app=await this.owned(userId,id);if(app.status!=='DRAFT')this.fail(HttpStatus.CONFLICT,'APPLICATION_ALREADY_SUBMITTED','This proposal is already submitted or awaiting payment.');await this.eligibility.require(userId,app.campaignId);const fee=await this.fees.resolve(app.campaignId,app.creatorId);if(app.applicationFeeMinor!=null&&(app.applicationFeeMinor!==fee.amountMinor||app.applicationFeeCurrencyCode!==fee.currencyCode)){await this.db.campaignApplication.update({where:{id},data:{applicationFeeMinor:fee.amountMinor,applicationFeeCurrencyCode:fee.currencyCode,applicationFeeRuleId:fee.ruleId}});this.fail(HttpStatus.CONFLICT,'APPLICATION_FEE_CHANGED','The Rivera Application Fee changed. Review the updated fee before continuing.');}if(fee.amountMinor===0)return{application:await this.submitWithoutPayment(userId,id,false),checkoutUrl:null};if(process.env.STRIPE_APPLICATION_FEE_ENABLED==='false')this.fail(HttpStatus.SERVICE_UNAVAILABLE,'PAYMENT_CREATION_FAILED','Application fee payments are temporarily unavailable.');const minutes=Math.max(30,Number(process.env.APPLICATION_PAYMENT_EXPIRY_MINUTES??30));const expiresAt=new Date(Date.now()+minutes*60_000);let payment;try{payment=await this.db.$transaction(async tx=>{const active=await tx.applicationPayment.findFirst({where:{applicationId:id,status:{in:['PENDING','PROCESSING']},expiresAt:{gt:new Date()}}});if(active)this.fail(HttpStatus.CONFLICT,'PAYMENT_ALREADY_PROCESSING','A payment is already being prepared for this proposal.');const created=await tx.applicationPayment.create({data:{applicationId:id,creatorId:app.creatorId,campaignId:app.campaignId,amountMinor:fee.amountMinor,currencyCode:fee.currencyCode,status:'PENDING',expiresAt}});await tx.campaignApplication.update({where:{id},data:{status:'AWAITING_PAYMENT',paymentStatus:'PENDING',applicationFeeMinor:fee.amountMinor,applicationFeeCurrencyCode:fee.currencyCode,applicationFeeRuleId:fee.ruleId}});await this.audit(tx,id,userId,'APPLICATION_PAYMENT_STARTED',{amountMinor:fee.amountMinor,currencyCode:fee.currencyCode});return created;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')this.fail(HttpStatus.CONFLICT,'PAYMENT_ALREADY_PROCESSING','A payment is already being prepared for this proposal.');throw error;}
    try{const checkout=await this.provider.createCheckout({paymentId:payment.id,applicationId:id,creatorId:app.creatorId,campaignId:app.campaignId,campaignTitle:app.campaign.title,amountMinor:fee.amountMinor,currencyCode:fee.currencyCode,expiresAt});await this.db.applicationPayment.update({where:{id:payment.id},data:{providerCheckoutSessionId:checkout.checkoutSessionId,providerPaymentId:checkout.paymentId}});return{checkoutUrl:checkout.url,expiresAt,applicationFeeMinor:fee.amountMinor,applicationFeeCurrencyCode:fee.currencyCode};}catch{await this.db.$transaction([this.db.applicationPayment.update({where:{id:payment.id},data:{status:'FAILED',failureCode:'PAYMENT_CREATION_FAILED',failureMessage:'Stripe Checkout could not be created.'}}),this.db.campaignApplication.update({where:{id},data:{status:'DRAFT',paymentStatus:'FAILED'}}),this.db.applicationAuditLog.create({data:{applicationId:id,actorUserId:userId,action:'APPLICATION_PAYMENT_FAILED'}})]);this.fail(HttpStatus.BAD_GATEWAY,'PAYMENT_CREATION_FAILED','Secure payment could not be prepared. Please try again.');}
  }

  async mine(userId:string,query:ApplicationQueryDto){const creator=await this.creator(userId);const where:Prisma.CampaignApplicationWhereInput={creatorId:creator.id,...(query.status?{status:query.status}:{})};const[items,total]=await this.db.$transaction([this.db.campaignApplication.findMany({where,include:applicationInclude,orderBy:{updatedAt:'desc'},skip:(query.page-1)*query.limit,take:query.limit}),this.db.campaignApplication.count({where})]);return{items:items.map(x=>this.ownDto(x)),pagination:{page:query.page,limit:query.limit,total,pages:Math.ceil(total/query.limit)}};}
  async detail(userId:string,id:string){return this.ownDto(await this.owned(userId,id));}
  async credits(userId:string){const creator=await this.creator(userId);const history=await this.db.applicationCreditTransaction.findMany({where:{creatorId:creator.id},orderBy:{createdAt:'desc'},take:50});return{balance:creator.freeApplicationCredits,history};}
  async payments(userId:string){const creator=await this.creator(userId);const items=await this.db.applicationPayment.findMany({where:{creatorId:creator.id},include:{application:{include:{campaign:{select:{title:true,slug:true}}}}},orderBy:{createdAt:'desc'}});return items.map(p=>({id:p.id,campaign:p.application.campaign,amountMinor:p.amountMinor,currencyCode:p.currencyCode,status:p.status,paidAt:p.paidAt,refundedAt:p.refundedAt,createdAt:p.createdAt,reference:this.shortRef(p.providerPaymentId??p.providerCheckoutSessionId)}));}
  async paymentStatus(userId:string,id:string){const app=await this.owned(userId,id);const latest=app.payments[0];if(latest&&['PENDING','PROCESSING'].includes(latest.status)&&latest.providerCheckoutSessionId){try{const state=await this.provider.retrievePayment({paymentId:latest.providerPaymentId,checkoutSessionId:latest.providerCheckoutSessionId});if(state.status==='paid')await this.activatePayment(latest.id,state,userId);}catch{/* webhook remains authoritative */}}return this.ownDto(await this.owned(userId,id));}
  async withdraw(userId:string,id:string){const app=await this.owned(userId,id);if(!['SUBMITTED','VIEWED'].includes(app.status))this.fail(HttpStatus.CONFLICT,app.status==='WITHDRAWN'?'APPLICATION_ALREADY_WITHDRAWN':'INVALID_APPLICATION_STATE','Only submitted proposals can be withdrawn.');const updated=await this.db.$transaction(async tx=>{const value=await tx.campaignApplication.update({where:{id},data:{status:'WITHDRAWN',withdrawnAt:new Date()},include:applicationInclude});await this.audit(tx,id,userId,'APPLICATION_WITHDRAWN');return value;});return this.ownDto(updated);}
  async unlocked(userId:string,campaignId:string){const creator=await this.creator(userId);const app=await this.db.campaignApplication.findUnique({where:{campaignId_creatorId:{campaignId,creatorId:creator.id}},include:{campaign:{include:campaignForApplication}}});if(!app||!['SUBMITTED','VIEWED','WITHDRAWN'].includes(app.status)||!['PAID','NOT_REQUIRED'].includes(app.paymentStatus))this.fail(HttpStatus.FORBIDDEN,'CAMPAIGN_BRIEF_LOCKED','Submit a valid proposal to unlock the full Campaign brief.');return this.unlockedCampaign(app.campaign);}

  private businessCampaign(userId:string,campaignId:string){return this.db.campaign.findFirst({where:{id:campaignId,business:{userId}},include:{business:true}}).then(c=>{if(!c)this.fail(HttpStatus.FORBIDDEN,'CAMPAIGN_OWNERSHIP_REQUIRED','You cannot access applications for this Campaign.');return c;});}
  async businessList(userId:string,campaignId:string,query:ApplicationQueryDto){await this.businessCampaign(userId,campaignId);const visible:ApplicationStatus[]=['SUBMITTED','VIEWED','WITHDRAWN'];const where:Prisma.CampaignApplicationWhereInput={campaignId,status:query.status&&visible.includes(query.status)?query.status:{in:visible},...(query.country?{creator:{country:query.country.toUpperCase()}}:{}),...(query.category?{creator:{categories:{some:{category:{slug:query.category}}}}}:{}),...(query.platform?{creator:{socialAccounts:{some:{platform:query.platform as any}}}}:{}),...(query.verified?{creator:{verificationStatus:'VERIFIED'}}:{})};const orderBy:Prisma.CampaignApplicationOrderByWithRelationInput=query.sort==='oldest'?{submittedAt:'asc'}:query.sort==='price-low'?{proposedAmountMinor:'asc'}:query.sort==='price-high'?{proposedAmountMinor:'desc'}:{submittedAt:'desc'};const[items,total]=await this.db.$transaction([this.db.campaignApplication.findMany({where,include:applicationInclude,orderBy,skip:(query.page-1)*query.limit,take:query.limit}),this.db.campaignApplication.count({where})]);return{items:items.map(x=>this.businessDto(x)),pagination:{page:query.page,limit:query.limit,total,pages:Math.ceil(total/query.limit)}};}
  async businessDetail(userId:string,campaignId:string,id:string){await this.businessCampaign(userId,campaignId);let app=await this.db.campaignApplication.findFirst({where:{id,campaignId,status:{in:['SUBMITTED','VIEWED','WITHDRAWN']}},include:applicationInclude});if(!app)this.fail(HttpStatus.NOT_FOUND,'APPLICATION_NOT_FOUND','Application not found.');if(app.status==='SUBMITTED'){app=await this.db.$transaction(async tx=>{const updated=await tx.campaignApplication.update({where:{id},data:{status:'VIEWED',viewedAt:new Date()},include:applicationInclude});await this.audit(tx,id,userId,'APPLICATION_VIEWED');await tx.notification.create({data:{userId:app!.creator.userId,creatorId:app!.creatorId,applicationId:id,type:'PROPOSAL_VIEWED',title:'Proposal viewed',body:`Your proposal for ${app!.campaign.title} was viewed.`}});return updated;});}return this.businessDto(app);}
  async businessSummary(userId:string){const business=await this.db.businessProfile.findUnique({where:{userId}});if(!business)this.fail(HttpStatus.BAD_REQUEST,'BUSINESS_PROFILE_REQUIRED','Complete your Business profile first.');const visible:ApplicationStatus[]=['SUBMITTED','VIEWED','WITHDRAWN'];const[received,viewed,recent]=await Promise.all([this.db.campaignApplication.count({where:{campaign:{businessId:business.id},status:{in:visible}}}),this.db.campaignApplication.count({where:{campaign:{businessId:business.id},status:'VIEWED'}}),this.db.campaignApplication.findMany({where:{campaign:{businessId:business.id},status:{in:visible}},include:applicationInclude,orderBy:{submittedAt:'desc'},take:5})]);return{applicationsReceived:received,applicationsViewed:viewed,recentApplications:recent.map(x=>this.businessDto(x))};}
  async creatorSummary(userId:string){const creator=await this.creator(userId);const[submitted,viewed,drafts,recent]=await Promise.all([this.db.campaignApplication.count({where:{creatorId:creator.id,status:{in:['SUBMITTED','VIEWED','WITHDRAWN']}}}),this.db.campaignApplication.count({where:{creatorId:creator.id,status:'VIEWED'}}),this.db.campaignApplication.count({where:{creatorId:creator.id,status:'DRAFT'}}),this.db.campaignApplication.findMany({where:{creatorId:creator.id},include:applicationInclude,orderBy:{updatedAt:'desc'},take:5})]);return{applicationsSubmitted:submitted,applicationsViewed:viewed,draftApplications:drafts,freeApplicationCredits:creator.freeApplicationCredits,recentApplications:recent.map(x=>this.ownDto(x))};}

  async notifications(userId:string){const [items,unread]=await Promise.all([this.db.notification.findMany({where:{userId},select:{id:true,type:true,title:true,body:true,readAt:true,createdAt:true,applicationId:true},orderBy:{createdAt:'desc'},take:50}),this.db.notification.count({where:{userId,readAt:null}})]);return{items,unread};}
  async markNotificationRead(userId:string,id:string){const changed=await this.db.notification.updateMany({where:{id,userId},data:{readAt:new Date()}});if(changed.count!==1)this.fail(HttpStatus.NOT_FOUND,'NOTIFICATION_NOT_FOUND','Notification not found.');return{success:true};}

  async handleWebhook(rawBody:Buffer,signature?:string){let event:VerifiedWebhook;try{event=this.provider.verifyWebhook(rawBody,signature);}catch{this.fail(HttpStatus.BAD_REQUEST,'INVALID_WEBHOOK_SIGNATURE','Webhook signature is invalid.');}try{await this.db.paymentWebhookEvent.create({data:{provider:'STRIPE',providerEventId:event.id,eventType:event.type,status:'PROCESSING'}});}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002')return{received:true,duplicate:true};throw error;}try{await this.processWebhook(event);await this.db.paymentWebhookEvent.update({where:{provider_providerEventId:{provider:'STRIPE',providerEventId:event.id}},data:{status:'PROCESSED',processedAt:new Date()}});return{received:true};}catch(error){const response=error instanceof ApiException?error.getResponse():null;const code=typeof response==='object'&&response&&'code' in response?String(response.code):'WEBHOOK_PROCESSING_FAILED';await this.db.paymentWebhookEvent.update({where:{provider_providerEventId:{provider:'STRIPE',providerEventId:event.id}},data:{status:'FAILED',errorCode:code,processedAt:new Date()}});return{received:true,handled:false,code};}}
  private async processWebhook(event:VerifiedWebhook){const object=event.object;let payment=typeof object.id==='string'?await this.db.applicationPayment.findFirst({where:{OR:[{providerPaymentId:object.id},{providerCheckoutSessionId:object.id}]}}):null;if(!payment&&typeof object.payment_intent==='string')payment=await this.db.applicationPayment.findUnique({where:{providerPaymentId:object.payment_intent}});const metadataPaymentId=typeof (object.metadata as any)?.paymentId==='string'?(object.metadata as any).paymentId:undefined;if(!payment&&metadataPaymentId)payment=await this.db.applicationPayment.findUnique({where:{id:metadataPaymentId}});if(!payment)this.fail(HttpStatus.NOT_FOUND,'PAYMENT_NOT_FOUND','Payment record was not found.');if(event.type==='checkout.session.completed'||event.type==='payment_intent.succeeded'){const state:ProviderPayment={paymentId:typeof object.payment_intent==='string'?object.payment_intent:payment.providerPaymentId??undefined,checkoutSessionId:event.type==='checkout.session.completed'?String(object.id):payment.providerCheckoutSessionId??undefined,status:'paid',amountMinor:Number(object.amount_total??object.amount_received??object.amount),currencyCode:String(object.currency).toUpperCase()};await this.activatePayment(payment.id,state,'stripe-webhook');return;}if(event.type==='payment_intent.payment_failed'||event.type==='checkout.session.expired'){await this.failPayment(payment.id,String((object.last_payment_error as any)?.code??'PAYMENT_FAILED'));return;}if(event.type==='charge.refunded'||event.type==='refund.updated'){await this.reconcileRefund(payment.id,object);}}
  private async activatePayment(paymentId:string,state:ProviderPayment,actorUserId:string){const payment=await this.db.applicationPayment.findUniqueOrThrow({where:{id:paymentId},include:{application:{include:{campaign:{include:{business:true}}}}}});if(payment.status==='PAID')return;if(state.amountMinor!==payment.amountMinor){await this.db.applicationPayment.update({where:{id:paymentId},data:{status:'FAILED',failureCode:'PAYMENT_AMOUNT_MISMATCH',failureMessage:'Provider amount did not match the expected fee.'}});this.fail(HttpStatus.CONFLICT,'PAYMENT_AMOUNT_MISMATCH','Payment amount requires support review.');}if(state.currencyCode!==payment.currencyCode){await this.db.applicationPayment.update({where:{id:paymentId},data:{status:'FAILED',failureCode:'PAYMENT_CURRENCY_MISMATCH',failureMessage:'Provider currency did not match the expected fee.'}});this.fail(HttpStatus.CONFLICT,'PAYMENT_CURRENCY_MISMATCH','Payment currency requires support review.');}const campaignClosed=payment.application.campaign.deletedAt||payment.application.campaign.status!=='OPEN'||(payment.application.campaign.applicationDeadline&&payment.application.campaign.applicationDeadline<=new Date());if(campaignClosed){await this.db.applicationPayment.update({where:{id:paymentId},data:{status:'PAID',providerPaymentId:state.paymentId,paidAt:new Date(),failureCode:'CAMPAIGN_CLOSED_REFUND_REQUIRED'}});this.fail(HttpStatus.CONFLICT,'CAMPAIGN_CLOSED_REFUND_REQUIRED','Payment requires an administrator refund because the Campaign is no longer accepting proposals.');}const updated=await this.db.$transaction(async tx=>{await tx.applicationPayment.update({where:{id:paymentId},data:{status:'PAID',providerPaymentId:state.paymentId,providerCheckoutSessionId:state.checkoutSessionId,paidAt:new Date(),failureCode:null,failureMessage:null}});const app=await tx.campaignApplication.update({where:{id:payment.applicationId},data:{status:'SUBMITTED',paymentStatus:'PAID',submittedAt:payment.application.submittedAt??new Date()},include:applicationInclude});await this.audit(tx,payment.applicationId,actorUserId,'APPLICATION_FEE_PAID',{amountMinor:payment.amountMinor,currencyCode:payment.currencyCode});await this.audit(tx,payment.applicationId,actorUserId,'APPLICATION_SUBMITTED',{method:'STRIPE'});await tx.notification.createMany({data:[{userId:app.creator.userId,creatorId:app.creatorId,applicationId:app.id,type:'PROPOSAL_SUBMITTED',title:'Proposal submitted',body:`Your proposal for ${app.campaign.title} was submitted successfully.`},{userId:payment.application.campaign.business.userId,businessId:payment.application.campaign.businessId,applicationId:app.id,type:'NEW_PROPOSAL',title:'New proposal received',body:`${app.creator.displayName} submitted a proposal for ${app.campaign.title}.`} ]});return app;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});void this.sendSubmissionEmails(updated);}
  private async failPayment(paymentId:string,code:string){const payment=await this.db.applicationPayment.findUniqueOrThrow({where:{id:paymentId},include:{application:{include:{creator:true}}}});if(['PAID','REFUNDED'].includes(payment.status))return;await this.db.$transaction(async tx=>{await tx.applicationPayment.update({where:{id:paymentId},data:{status:'FAILED',failureCode:code,failureMessage:'Payment was not completed.'}});await tx.campaignApplication.update({where:{id:payment.applicationId},data:{status:'DRAFT',paymentStatus:'FAILED'}});await this.audit(tx,payment.applicationId,payment.application.creator.userId,'APPLICATION_PAYMENT_FAILED',{code});});}
  private async reconcileRefund(paymentId:string,object:Record<string,unknown>){const payment=await this.db.applicationPayment.findUniqueOrThrow({where:{id:paymentId}});const reported=Number(object.amount_refunded??object.amount??payment.amountMinor);const refundedAmountMinor=Math.min(payment.amountMinor,Math.max(payment.refundedAmountMinor??0,Number.isFinite(reported)?reported:payment.amountMinor));const fullyRefunded=Boolean(object.refunded)||refundedAmountMinor>=payment.amountMinor;await this.db.$transaction([this.db.applicationPayment.update({where:{id:paymentId},data:{status:fullyRefunded?'REFUNDED':'PARTIALLY_REFUNDED',refundedAmountMinor,refundedAt:new Date()}}),this.db.campaignApplication.update({where:{id:payment.applicationId},data:{paymentStatus:fullyRefunded?'REFUNDED':'PARTIALLY_REFUNDED'}})]);}
  private async sendSubmissionEmails(app:any){const [creatorUser,business]=await Promise.all([this.db.user.findUnique({where:{id:app.creator.userId}}),this.db.businessProfile.findUnique({where:{id:app.campaign.businessId},include:{user:true}})]);if(creatorUser)void this.mail.sendMarketplaceEmail(creatorUser.email,'Proposal submitted',`Your proposal for ${app.campaign.title} was submitted successfully.`);if(business)void this.mail.sendMarketplaceEmail(business.user.email,'New proposal received',`${app.creator.displayName} submitted a proposal for ${app.campaign.title}.`);}

  async adminApplications(query:ApplicationQueryDto){const where:Prisma.CampaignApplicationWhereInput=query.status?{status:query.status}:{};const[items,total]=await this.db.$transaction([this.db.campaignApplication.findMany({where,include:applicationInclude,orderBy:{updatedAt:'desc'},skip:(query.page-1)*query.limit,take:query.limit}),this.db.campaignApplication.count({where})]);return{items:items.map(a=>({...this.businessDto(a),campaign:{id:a.campaign.id,title:a.campaign.title,business:a.campaign.business},paymentStatus:a.paymentStatus,applicationFeeMinor:a.applicationFeeMinor,applicationFeeCurrencyCode:a.applicationFeeCurrencyCode,usedFreeCredit:a.usedFreeCredit})),pagination:{page:query.page,limit:query.limit,total,pages:Math.ceil(total/query.limit)}};}
  feeRules(){return this.db.applicationFeeRule.findMany({include:{category:true},orderBy:[{priority:'desc'},{createdAt:'desc'}]});}
  createFeeRule(dto:FeeRuleDto){return this.db.applicationFeeRule.create({data:{...dto,countryCode:dto.countryCode||null,categoryId:dto.categoryId||null,currencyCode:dto.currencyCode.toUpperCase(),startsAt:dto.startsAt?new Date(dto.startsAt):null,endsAt:dto.endsAt?new Date(dto.endsAt):null}});}
  async updateFeeRule(id:string,dto:FeeRuleDto){if(!await this.db.applicationFeeRule.findUnique({where:{id}}))this.fail(HttpStatus.NOT_FOUND,'FEE_RULE_NOT_FOUND','Fee rule not found.');return this.db.applicationFeeRule.update({where:{id},data:{...dto,countryCode:dto.countryCode||null,categoryId:dto.categoryId||null,currencyCode:dto.currencyCode.toUpperCase(),startsAt:dto.startsAt?new Date(dto.startsAt):null,endsAt:dto.endsAt?new Date(dto.endsAt):null}});}
  async grantCredits(adminUserId:string,creatorId:string,dto:CreditGrantDto){if(!await this.db.creatorProfile.findUnique({where:{id:creatorId}}))this.fail(HttpStatus.NOT_FOUND,'CREATOR_PROFILE_NOT_FOUND','Creator profile not found.');return this.db.$transaction(async tx=>{const creator=await tx.creatorProfile.update({where:{id:creatorId},data:{freeApplicationCredits:{increment:dto.quantity}}});const ledger=await tx.applicationCreditTransaction.create({data:{creatorId,type:'GRANT',quantity:dto.quantity,balanceAfter:creator.freeApplicationCredits,reason:dto.reason,referenceId:`admin:${adminUserId}:${Date.now()}`}});return{balance:creator.freeApplicationCredits,transaction:ledger};});}
  async adminPayments(){const items=await this.db.applicationPayment.findMany({include:{application:{include:{campaign:{include:{business:{select:safeBusiness}}},creator:{include:creatorProfileInclude}}},refunds:true},orderBy:{createdAt:'desc'}});return items.map(p=>({...p,providerPaymentId:this.shortRef(p.providerPaymentId),providerCheckoutSessionId:this.shortRef(p.providerCheckoutSessionId),application:{id:p.application.id,status:p.application.status,campaign:{id:p.application.campaign.id,title:p.application.campaign.title,business:p.application.campaign.business},creator:this.safeCreator(p.application.creator)}}));}
  async adminPayment(id:string){const p=await this.db.applicationPayment.findUnique({where:{id},include:{application:{include:applicationInclude},refunds:true}});if(!p)this.fail(HttpStatus.NOT_FOUND,'PAYMENT_NOT_FOUND','Payment not found.');const events=await this.db.paymentWebhookEvent.findMany({where:{provider:'STRIPE'},orderBy:{createdAt:'desc'},take:20});return{...p,application:{...this.businessDto(p.application),campaign:{id:p.application.campaign.id,title:p.application.campaign.title,business:p.application.campaign.business}},webhookEvents:events};}
  async refund(adminUserId:string,id:string,dto:RefundDto){const payment=await this.db.applicationPayment.findUnique({where:{id},include:{application:{include:{campaign:true}}}});if(!payment)this.fail(HttpStatus.NOT_FOUND,'PAYMENT_NOT_FOUND','Payment not found.');if(payment.status!=='PAID'||payment.refundedAmountMinor>0||!payment.providerPaymentId)this.fail(HttpStatus.CONFLICT,'INVALID_PAYMENT_STATE','Only an unrefunded paid fee can be refunded.');let refund;try{refund=await this.provider.refund(payment.providerPaymentId,payment.amountMinor,`rivera-refund-${payment.id}`);}catch{this.fail(HttpStatus.BAD_GATEWAY,'REFUND_FAILED','Stripe could not complete this refund.');}return this.db.$transaction(async tx=>{const record=await tx.paymentRefund.create({data:{paymentId:id,providerRefundId:refund.refundId,amountMinor:payment.amountMinor,currencyCode:payment.currencyCode,reason:dto.reason,note:dto.note,requestedByAdminId:adminUserId,status:refund.status==='succeeded'?'SUCCEEDED':refund.status==='failed'?'FAILED':'PENDING',completedAt:refund.status==='succeeded'?new Date():null}});if(refund.status==='succeeded'){await tx.applicationPayment.update({where:{id},data:{status:'REFUNDED',refundedAmountMinor:payment.amountMinor,refundedAt:new Date()}});await tx.campaignApplication.update({where:{id:payment.applicationId},data:{paymentStatus:'REFUNDED',...(payment.application.campaign.status==='CANCELLED'?{status:'CANCELLED'}:{})}});await this.audit(tx,payment.applicationId,adminUserId,'APPLICATION_FEE_REFUNDED',{reason:dto.reason,amountMinor:payment.amountMinor});}return record;});}
}
