import { createHmac, timingSafeEqual } from 'node:crypto';

export type CheckoutInput = { paymentId:string; applicationId:string; creatorId:string; campaignId:string; campaignTitle:string; amountMinor:number; currencyCode:string; expiresAt:Date };
export type CheckoutResult = { checkoutSessionId:string; paymentId?:string; url:string };
export type ProviderPayment = { paymentId?:string; checkoutSessionId?:string; status:'paid'|'pending'|'failed'|'refunded'; amountMinor:number; currencyCode:string };
export type ProviderRefund = { refundId:string; status:'pending'|'succeeded'|'failed' };
export type VerifiedWebhook = { id:string; type:string; object:Record<string,unknown> };
export type ConnectedAccount = { accountId:string; countryCode:string; defaultCurrencyCode?:string; chargesEnabled:boolean; payoutsEnabled:boolean; detailsSubmitted:boolean; requirementsDue:string[] };
export type CollaborationCheckoutInput = { collaborationPaymentId:string; participantId:string; businessId:string; campaignTitle:string; creatorName:string; amountMinor:number; currencyCode:string; expiresAt:Date; attemptKey:string };
export type ProviderTransfer = { transferId:string; status:'pending'|'succeeded'|'failed'; failureCode?:string; failureMessage?:string };
export interface PaymentProviderAdapter {
  createCheckout(input:CheckoutInput):Promise<CheckoutResult>;
  retrievePayment(reference:{paymentId?:string|null;checkoutSessionId?:string|null}):Promise<ProviderPayment>;
  refund(paymentId:string,amountMinor:number,idempotencyKey:string):Promise<ProviderRefund>;
  retrieveRefund(refundId:string):Promise<ProviderRefund>;
  verifyWebhook(rawBody:Buffer,signature?:string):VerifiedWebhook;
  createConnectedAccount(input:{creatorId:string;countryCode:string;email:string}):Promise<ConnectedAccount>;
  createAccountOnboardingLink(accountId:string,returnUrl:string,refreshUrl:string):Promise<{url:string}>;
  retrieveConnectedAccount(accountId:string):Promise<ConnectedAccount>;
  createCollaborationPayment(input:CollaborationCheckoutInput):Promise<CheckoutResult>;
  createTransfer(input:{collaborationPaymentId:string;accountId:string;amountMinor:number;currencyCode:string;idempotencyKey:string}):Promise<ProviderTransfer>;
  retrieveTransfer(transferId:string):Promise<ProviderTransfer>;
}
export const PAYMENT_PROVIDER = Symbol('APPLICATION_PAYMENT_PROVIDER');

export class StripePaymentProvider implements PaymentProviderAdapter {
  private secret(){const key=process.env.STRIPE_SECRET_KEY;if(!key)throw new Error('STRIPE_NOT_CONFIGURED');return key;}
  private async request(path:string,body?:URLSearchParams,idempotencyKey?:string){const response=await fetch(`https://api.stripe.com/v1/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${this.secret()}`,...(body?{'Content-Type':'application/x-www-form-urlencoded'}:{}),...(idempotencyKey?{'Idempotency-Key':idempotencyKey}:{})},body});const value=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(typeof (value.error as Record<string,unknown>)?.code==='string'?String((value.error as Record<string,unknown>).code):'STRIPE_REQUEST_FAILED');return value;}
  async createCheckout(input:CheckoutInput){const app=process.env.APP_URL??'http://localhost:3000';const body=new URLSearchParams({'mode':'payment','success_url':`${app}/dashboard/creator/applications/${input.applicationId}?payment=success`,'cancel_url':`${app}/dashboard/creator/applications/${input.applicationId}?payment=cancelled`,'expires_at':String(Math.floor(input.expiresAt.getTime()/1000)),'line_items[0][price_data][currency]':input.currencyCode.toLowerCase(),'line_items[0][price_data][unit_amount]':String(input.amountMinor),'line_items[0][price_data][product_data][name]':'Rivera Application Fee','line_items[0][price_data][product_data][description]':`Submit proposal for ${input.campaignTitle}`,'line_items[0][quantity]':'1','metadata[applicationId]':input.applicationId,'metadata[paymentId]':input.paymentId,'payment_intent_data[metadata][applicationId]':input.applicationId,'payment_intent_data[metadata][paymentId]':input.paymentId});const value=await this.request('checkout/sessions',body,`rivera-checkout-${input.paymentId}`);return{checkoutSessionId:String(value.id),paymentId:typeof value.payment_intent==='string'?value.payment_intent:undefined,url:String(value.url)};}
  async retrievePayment(reference:{paymentId?:string|null;checkoutSessionId?:string|null}):Promise<ProviderPayment>{let value:Record<string,unknown>;if(reference.paymentId)value=await this.request(`payment_intents/${encodeURIComponent(reference.paymentId)}`);else if(reference.checkoutSessionId)value=await this.request(`checkout/sessions/${encodeURIComponent(reference.checkoutSessionId)}`);else throw new Error('PAYMENT_REFERENCE_MISSING');const status=String(value.payment_status??value.status);const normalized:ProviderPayment['status']=status==='paid'||status==='succeeded'?'paid':status==='failed'||status==='canceled'?'failed':'pending';return{paymentId:typeof value.payment_intent==='string'?value.payment_intent:reference.paymentId??undefined,checkoutSessionId:reference.checkoutSessionId??undefined,status:normalized,amountMinor:Number(value.amount_total??value.amount_received??value.amount??0),currencyCode:String(value.currency??'').toUpperCase()};}
  async refund(paymentId:string,amountMinor:number,idempotencyKey:string):Promise<ProviderRefund>{const value=await this.request('refunds',new URLSearchParams({payment_intent:paymentId,amount:String(amountMinor)}),idempotencyKey);const status:ProviderRefund['status']=String(value.status)==='succeeded'?'succeeded':String(value.status)==='failed'?'failed':'pending';return{refundId:String(value.id),status};}
  async retrieveRefund(refundId:string):Promise<ProviderRefund>{const value=await this.request(`refunds/${encodeURIComponent(refundId)}`);const status:ProviderRefund['status']=String(value.status)==='succeeded'?'succeeded':String(value.status)==='failed'||String(value.status)==='canceled'?'failed':'pending';return{refundId:String(value.id),status};}
  private account(value:Record<string,unknown>):ConnectedAccount{const requirements=(value.requirements??{}) as Record<string,unknown>;return{accountId:String(value.id),countryCode:String(value.country??'').toUpperCase(),defaultCurrencyCode:typeof value.default_currency==='string'?value.default_currency.toUpperCase():undefined,chargesEnabled:Boolean(value.charges_enabled),payoutsEnabled:Boolean(value.payouts_enabled),detailsSubmitted:Boolean(value.details_submitted),requirementsDue:Array.isArray(requirements.currently_due)?requirements.currently_due.map(String):[]};}
  async createConnectedAccount(input:{creatorId:string;countryCode:string;email:string}){return this.account(await this.request('accounts',new URLSearchParams({type:'express',country:input.countryCode.toUpperCase(),email:input.email,'capabilities[transfers][requested]':'true','metadata[creatorId]':input.creatorId}),`rivera-connect-${input.creatorId}`));}
  async createAccountOnboardingLink(accountId:string,returnUrl:string,refreshUrl:string){const value=await this.request('account_links',new URLSearchParams({account:accountId,type:'account_onboarding',return_url:returnUrl,refresh_url:refreshUrl}));return{url:String(value.url)};}
  async retrieveConnectedAccount(accountId:string){return this.account(await this.request(`accounts/${encodeURIComponent(accountId)}`));}
  async createCollaborationPayment(input:CollaborationCheckoutInput){const app=process.env.APP_URL??'http://localhost:3000';const body=new URLSearchParams({mode:'payment',success_url:`${app}/dashboard/business/payments?funding=processing`,cancel_url:`${app}/dashboard/business/payments?funding=cancelled`,expires_at:String(Math.floor(input.expiresAt.getTime()/1000)),'line_items[0][price_data][currency]':input.currencyCode.toLowerCase(),'line_items[0][price_data][unit_amount]':String(input.amountMinor),'line_items[0][price_data][product_data][name]':`Fund ${input.campaignTitle}`,'line_items[0][price_data][product_data][description]':`Creator collaboration with ${input.creatorName}`,'line_items[0][quantity]':'1','metadata[collaborationPaymentId]':input.collaborationPaymentId,'metadata[participantId]':input.participantId,'payment_intent_data[metadata][collaborationPaymentId]':input.collaborationPaymentId,'payment_intent_data[metadata][participantId]':input.participantId});const value=await this.request('checkout/sessions',body,`rivera-collaboration-checkout-${input.collaborationPaymentId}-${input.attemptKey}`);return{checkoutSessionId:String(value.id),paymentId:typeof value.payment_intent==='string'?value.payment_intent:undefined,url:String(value.url)};}
  async createTransfer(input:{collaborationPaymentId:string;accountId:string;amountMinor:number;currencyCode:string;idempotencyKey:string}){const value=await this.request('transfers',new URLSearchParams({destination:input.accountId,amount:String(input.amountMinor),currency:input.currencyCode.toLowerCase(),'metadata[collaborationPaymentId]':input.collaborationPaymentId}),input.idempotencyKey);return{transferId:String(value.id),status:'pending' as const};}
  async retrieveTransfer(transferId:string){const value=await this.request(`transfers/${encodeURIComponent(transferId)}`);return{transferId:String(value.id),status:Boolean(value.reversed)?'failed':'succeeded'} as ProviderTransfer;}
  verifyWebhook(rawBody:Buffer,signature?:string){const secret=process.env.STRIPE_WEBHOOK_SECRET;if(!secret||!signature)throw new Error('INVALID_WEBHOOK_SIGNATURE');const parts=Object.fromEntries(signature.split(',').map(item=>item.split('=',2)));const timestamp=Number(parts.t),provided=parts.v1;if(!timestamp||!provided||Math.abs(Date.now()/1000-timestamp)>300)throw new Error('INVALID_WEBHOOK_SIGNATURE');const expected=createHmac('sha256',secret).update(`${timestamp}.${rawBody.toString('utf8')}`).digest('hex');const a=Buffer.from(expected),b=Buffer.from(provided);if(a.length!==b.length||!timingSafeEqual(a,b))throw new Error('INVALID_WEBHOOK_SIGNATURE');const event=JSON.parse(rawBody.toString('utf8')) as {id:string;type:string;data:{object:Record<string,unknown>}};return{id:event.id,type:event.type,object:event.data.object};}
}
