'use client';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { api, ApiError } from '@/lib/api';
const message=(error:unknown)=>error instanceof ApiError?error.message:'Please try again.';
function AdminShell({title,children}:{title:string;children:React.ReactNode}){return <main className="profile-shell"><nav className="admin-nav"><Link href="/admin">Admin</Link><Link href="/admin/creators">Creators</Link><Link href="/admin/businesses">Businesses</Link><Link href="/admin/verifications">Verifications</Link><Link href="/admin/categories">Categories</Link><Link href="/admin/industries">Industries</Link><Link href="/admin/content-types">Content types</Link></nav><p className="eyebrow">RIVERA ADMINISTRATION</p><h1>{title}</h1>{children}</main>}
export function TaxonomyManager({kind}:{kind:'categories'|'industries'|'content-types'}){const [items,setItems]=useState<{id:string;name:string;slug:string;active:boolean;sortOrder:number}[]>([]);const [name,setName]=useState('');const [feedback,setFeedback]=useState('');const load=()=>api<typeof items>(`/${kind}`).then(setItems).catch(e=>setFeedback(message(e)));useEffect(()=>{void load()},[kind]);async function add(event:FormEvent){event.preventDefault();try{await api(`/admin/${kind}`,{method:'POST',body:JSON.stringify({name,sortOrder:items.length})});setName('');setFeedback('Record created.');void load()}catch(e){setFeedback(message(e))}}async function toggle(item:typeof items[number]){try{await api(`/admin/${kind}/${item.id}`,{method:'PATCH',body:JSON.stringify({name:item.name,active:!item.active,sortOrder:item.sortOrder})});setFeedback('Record updated.');void load()}catch(e){setFeedback(message(e))}}return <AdminShell title={kind.replaceAll('-',' ')}>{feedback&&<p className="form-success">{feedback}</p>}<form className="inline-form" onSubmit={add}><label className="field">Name<input required value={name} onChange={e=>setName(e.target.value)}/></label><button className="button primary">Create</button></form><div className="manage-list">{items.map(item=><article key={item.id}><div><strong>{item.name}</strong><p>/{item.slug} · order {item.sortOrder}</p></div><button onClick={()=>void toggle(item)}>{item.active?'Deactivate':'Activate'}</button></article>)}</div></AdminShell>}
type Verification={id:string;profileType:string;status:string;noteFromUser?:string;createdAt:string;user:{firstName:string;lastName:string};creatorProfile?:{slug:string;displayName:string};businessProfile?:{slug:string;name:string}};
type AdminProfile={id:string;displayName?:string;name?:string;slug:string;profileVisibility:string;verificationStatus:string;user:{status:string}};
export function VerificationQueue(){const [items,setItems]=useState<Verification[]>([]);const [feedback,setFeedback]=useState('');const load=()=>api<Verification[]>('/admin/verifications').then(setItems).catch(e=>setFeedback(message(e)));useEffect(()=>{void load()},[]);async function review(id:string,action:'approve'|'reject'){const note=window.prompt('Optional internal review note')||undefined;try{await api(`/admin/verifications/${id}/${action}`,{method:'POST',body:JSON.stringify({reviewNote:note})});setFeedback(`Request ${action}d.`);void load()}catch(e){setFeedback(message(e))}}return <AdminShell title="Verification queue">{feedback&&<p className="form-success">{feedback}</p>}<div className="manage-list">{items.map(item=><article key={item.id}><div><strong>{item.creatorProfile?.displayName||item.businessProfile?.name} · {item.profileType}</strong><p>{item.user.firstName} {item.user.lastName} · {item.status} · {new Date(item.createdAt).toLocaleDateString()}</p>{item.noteFromUser&&<p>{item.noteFromUser}</p>}</div>{item.status==='PENDING'&&<div><button onClick={()=>void review(item.id,'approve')}>Approve</button><button onClick={()=>void review(item.id,'reject')}>Reject</button></div>}</article>)}</div></AdminShell>}
export function ProfileAdminList({type}:{type:'creators'|'businesses'}){const [items,setItems]=useState<AdminProfile[]>([]);const [q,setQ]=useState('');const [feedback,setFeedback]=useState('');async function load(search=''){try{setItems(await api<AdminProfile[]>(`/admin/${type}${search?`?q=${encodeURIComponent(search)}`:''}`))}catch(e){setFeedback(message(e))}}useEffect(()=>{void load()},[type]);return <AdminShell title={type}><form className="inline-form" onSubmit={e=>{e.preventDefault();void load(q)}}><label className="field">Search<input value={q} onChange={e=>setQ(e.target.value)}/></label><button className="button primary">Search</button></form>{feedback&&<p className="form-error">{feedback}</p>}<div className="manage-list">{items.map(item=><article key={item.id}><div><strong>{item.displayName||item.name}</strong><p>/{item.slug} · {item.profileVisibility} · {item.verificationStatus} · account {item.user.status}</p></div><Link href={`/${type}/${item.slug}`}>View public profile</Link></article>)}</div></AdminShell>}
