'use client';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { Campaign, CampaignResult, objectives, platforms } from '@/lib/campaigns';
import { CampaignCard } from './campaign-card';

export function CreatorOpportunities({mode='browse'}:{mode?:'browse'|'saved'|'recommended'}){
 const [items,setItems]=useState<Campaign[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[filters,setFilters]=useState({q:'',country:'',city:'',category:'',platform:'',objective:'',locationType:'',sort:'newest'});
 const load=()=>{setLoading(true);setError('');const path=mode==='saved'?'/creator/campaigns/saved/list':mode==='recommended'?'/creator/campaigns/recommended/list':`/campaigns?${new URLSearchParams(Object.entries(filters).filter(([,value])=>value))}`;api<CampaignResult|Campaign[]>(path).then(value=>setItems(Array.isArray(value)?value:value.items)).catch(e=>setError(e instanceof ApiError?e.message:'Could not load opportunities.')).finally(()=>setLoading(false))};
 useEffect(load,[mode]);
 async function save(id:string,saved:boolean){try{await api(`/creator/campaigns/${id}/save`,{method:saved?'DELETE':'POST'});if(mode==='saved')load();}catch(e){setError(e instanceof ApiError?e.message:'Could not update this opportunity.')}}
 const title=mode==='saved'?'Saved opportunities':mode==='recommended'?'Recommended for you':'Find your next collaboration';
 return <main className="opportunity-shell"><header><Link href="/dashboard/creator">← Dashboard</Link><p className="eyebrow">CREATOR OPPORTUNITIES</p><h1>{title}</h1><p>{mode==='recommended'?'Recommendations use your categories, platforms, location, languages and verification state.':'Compare requirements, budgets and deadlines before saving the right opportunities.'}</p><nav className="opportunity-tabs"><Link href="/dashboard/creator/opportunities">Browse</Link><Link href="/dashboard/creator/opportunities/recommended">Recommended</Link><Link href="/dashboard/creator/saved-campaigns">Saved</Link></nav></header>{mode==='browse'&&<form className="campaign-filter-grid" onSubmit={e=>{e.preventDefault();load()}}><label>Search<input value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></label><label>Country<input maxLength={2} placeholder="QA" value={filters.country} onChange={e=>setFilters({...filters,country:e.target.value.toUpperCase()})}/></label><label>City<input value={filters.city} onChange={e=>setFilters({...filters,city:e.target.value})}/></label><label>Platform<select value={filters.platform} onChange={e=>setFilters({...filters,platform:e.target.value})}><option value="">All platforms</option>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label>Objective<select value={filters.objective} onChange={e=>setFilters({...filters,objective:e.target.value})}><option value="">All objectives</option>{objectives.map(x=><option key={x}>{x}</option>)}</select></label><label>Location<select value={filters.locationType} onChange={e=>setFilters({...filters,locationType:e.target.value})}><option value="">Any</option>{['LOCAL','NATIONAL','GLOBAL','REMOTE'].map(x=><option key={x}>{x}</option>)}</select></label><label>Sort<select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="newest">Newest</option><option value="deadline">Closing soon</option><option value="budget-high">Highest budget</option><option value="budget-low">Lowest budget</option></select></label><button className="button primary">Apply filters</button></form>}{error&&<p className="form-error">{error}</p>}{loading?<p>Loading opportunities…</p>:items.length?<div className="campaign-grid">{items.map(c=><CampaignCard key={c.id} campaign={c} action={<button className="save-campaign" onClick={()=>void save(c.id,mode==='saved')}>{mode==='saved'?'Remove':'Save opportunity'}</button>}/>)}</div>:<div className="dashboard-empty"><h2>{mode==='saved'?'No saved opportunities yet.':'No campaigns match right now.'}</h2><p>{mode==='saved'?'Browse Rivera and save campaigns you want to revisit.':'Try broader filters or check again as businesses publish new opportunities.'}</p></div>}</main>
}

export function SaveCampaign({id}:{id:string}){const [saved,setSaved]=useState(false),[notice,setNotice]=useState('');async function toggle(){try{await api(`/creator/campaigns/${id}/save`,{method:saved?'DELETE':'POST'});setSaved(!saved);setNotice(saved?'Removed from saved opportunities.':'Opportunity saved.')}catch(e){setNotice(e instanceof ApiError?e.message:'Sign in as a Creator to save this opportunity.')}}return <div className="save-area"><button className="button primary" onClick={()=>void toggle()}>{saved?'Remove saved opportunity':'Save opportunity'}</button>{notice&&<p role="status">{notice}</p>}</div>}
