'use client';
/* eslint-disable react-hooks/exhaustive-deps */
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { Campaign, CampaignResult, label, location } from '@/lib/campaigns';
import { AdminShell } from './admin-phase3';
const message=(error:unknown)=>error instanceof ApiError?error.message:'Please try again.';
export function CampaignAdminList(){const [result,setResult]=useState<CampaignResult|null>(null),[q,setQ]=useState(''),[error,setError]=useState('');const load=()=>api<CampaignResult>(`/admin/campaigns${q?`?q=${encodeURIComponent(q)}`:''}`).then(setResult).catch(e=>setError(message(e)));useEffect(()=>{void load()},[]);return <AdminShell title="Campaign moderation"><form className="inline-form" onSubmit={e=>{e.preventDefault();load()}}><label className="field">Search title or Business<input value={q} onChange={e=>setQ(e.target.value)}/></label><button className="button primary">Search</button></form>{error&&<p className="form-error">{error}</p>}<div className="manage-list">{result?.items.map(c=><article key={c.id}><div><strong>{c.title}</strong><p>{c.business.name} · {c.status} · {c.visibility} · {location(c)}</p></div><Link href={`/admin/campaigns/${c.id}`}>Inspect full brief</Link></article>)}</div></AdminShell>}
export function CampaignAdminDetail({id}:{id:string}){const [c,setCampaign]=useState<Campaign|null>(null),[feedback,setFeedback]=useState('');const load=()=>api<Campaign>(`/admin/campaigns/${id}`).then(setCampaign).catch(e=>setFeedback(message(e)));useEffect(()=>{void load()},[id]);async function update(data:Record<string,unknown>){try{await api(`/admin/campaigns/${id}`,{method:'PATCH',body:JSON.stringify(data)});setFeedback('Campaign moderation updated.');load()}catch(e){setFeedback(message(e))}}return <AdminShell title="Campaign inspection">{feedback&&<p className="form-success">{feedback}</p>}{c&&<><section className="profile-panel"><p className="eyebrow">{c.status} · {c.visibility}</p><h2>{c.title}</h2><p>{c.shortDescription}</p><p>{c.business.name} · {location(c)} · {label(c.campaignObjective)}</p><div className="dashboard-actions"><Link className="button secondary" href={`/campaigns/${c.slug}`}>Public summary</Link><button className="button secondary" onClick={()=>void update({isFeatured:!c.isFeatured})}>{c.isFeatured?'Remove featured':'Feature campaign'}</button><button className="button secondary" onClick={()=>void update({visibility:c.visibility==='PRIVATE'?'PUBLIC':'PRIVATE'})}>{c.visibility==='PRIVATE'?'Make public':'Set private'}</button>{c.status==='OPEN'&&<button className="button secondary" onClick={()=>void update({status:'PAUSED'})}>Pause campaign</button>}{['OPEN','PAUSED'].includes(c.status)&&<button className="button secondary" onClick={()=>void update({status:'CLOSED'})}>Close campaign</button>}<button className="button secondary" onClick={()=>void update({status:'CANCELLED'})}>Cancel campaign</button></div></section><section className="profile-panel locked-brief"><p className="eyebrow">OWNER/ADMIN ONLY</p><h2>Full brief</h2><p>{c.fullDescription}</p><h3>Target audience</h3><p>{c.targetAudience}</p><h3>Expected outcomes</h3><p>{c.expectedOutcomes}</p><h3>Special instructions</h3><p>{c.specialInstructions||'None'}</p></section></>}</AdminShell>}
