'use client';
/* eslint-disable react-hooks/exhaustive-deps */
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useState } from 'react';
import { api, ApiError } from '@/lib/api';
import { budget, Campaign, deadline, label, location, objectives, platforms } from '@/lib/campaigns';
import { countryOptions } from '@/lib/countries';

type Taxonomy={id:string;name:string;slug:string};
const empty={title:'',shortDescription:'',fullDescription:'',productOrServiceName:'',productOrServiceDescription:'',productUrl:'',campaignObjective:'BRAND_AWARENESS',targetAudience:'',expectedOutcomes:'',locationType:'GLOBAL',campaignCountryCode:'',campaignCity:'',campaignRegion:'',verifiedCreatorsOnly:false,categoryIds:[] as string[],creatorLocations:[] as {countryCode:string;city?:string}[],platforms:[] as {platform:string;required:boolean;minimumFollowers?:number}[],languages:[{languageCode:'en',required:true}],deliverables:[] as {title:string;description?:string;quantity:number;platform?:string;contentTypeId?:string;dueDate?:string}[],usageRights:'TO_BE_DISCUSSED',usageRightsNotes:'',productProvided:false,travelExpensesCovered:false,specialInstructions:'',budgetMinMinor:undefined as number|undefined,budgetMaxMinor:undefined as number|undefined,currencyCode:'USD',budgetVisibility:'PUBLIC',creatorSlots:1,applicationDeadline:'',campaignStartDate:'',campaignEndDate:'',visibility:'PUBLIC'};

export function CampaignWizard({campaignId}:{campaignId?:string}){
  const router=useRouter();
  const [step,setStep]=useState(1),[id,setId]=useState(campaignId),[form,setForm]=useState({...empty}),[categories,setCategories]=useState<Taxonomy[]>([]),[contentTypes,setContentTypes]=useState<Taxonomy[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([api<Taxonomy[]>('/categories'),api<Taxonomy[]>('/content-types')]).then(([a,b])=>{setCategories(a);setContentTypes(b)});if(campaignId)api<Campaign>(`/business/campaigns/${campaignId}`).then(c=>setForm({...empty,...c,budgetMinMinor:c.budgetMinMinor??undefined,budgetMaxMinor:c.budgetMaxMinor??undefined,categoryIds:c.categories.map(x=>x.categoryId??x.category?.id??x.id),creatorLocations:c.creatorLocations.map(x=>({countryCode:x.countryCode,city:x.city})),deliverables:c.deliverables.map(x=>({...x,dueDate:x.dueDate?.slice(0,10)})),applicationDeadline:c.applicationDeadline?.slice(0,10)??'',campaignStartDate:c.campaignStartDate?.slice(0,10)??'',campaignEndDate:c.campaignEndDate?.slice(0,10)??''})).catch(e=>setError(message(e)));},[campaignId]);
  const patch=(value:Partial<typeof form>)=>setForm(current=>({...current,...value}));
  const payload=()=>{
    const flexibleLocation=['GLOBAL','REMOTE'].includes(form.locationType);
    const countryCode=form.campaignCountryCode.trim().toUpperCase();
    const city=form.campaignCity.trim();
    return {...form,
      applicationDeadline:form.applicationDeadline?new Date(`${form.applicationDeadline}T23:59:59Z`).toISOString():undefined,
      campaignStartDate:form.campaignStartDate?new Date(`${form.campaignStartDate}T12:00:00Z`).toISOString():undefined,
      campaignEndDate:form.campaignEndDate?new Date(`${form.campaignEndDate}T12:00:00Z`).toISOString():undefined,
      budgetMinMinor:form.budgetMinMinor,budgetMaxMinor:form.budgetMaxMinor,
      campaignCountryCode:!flexibleLocation&&countryCode?countryCode:undefined,
      campaignCity:form.locationType==='LOCAL'&&city?city:undefined,
      campaignRegion:!flexibleLocation&&form.campaignRegion.trim()?form.campaignRegion.trim():undefined,
      creatorLocations:!flexibleLocation&&countryCode?[{countryCode,city:form.locationType==='LOCAL'&&city?city:undefined}]:[],
      productUrl:form.productUrl.trim()||undefined,
    };
  };
  async function save(show=true){setBusy(true);setError('');try{const campaign=await api<Campaign>(id?`/business/campaigns/${id}`:'/business/campaigns',{method:id?'PATCH':'POST',body:JSON.stringify(payload())});setId(campaign.id);if(show)setNotice('Draft saved.');return campaign;}catch(e){setError(message(e));return null}finally{setBusy(false)}}
  async function next(){const saved=await save(false);if(saved)setStep(value=>Math.min(5,value+1));}
  async function publish(){const saved=await save(false);if(!saved)return;setBusy(true);try{await api(`/business/campaigns/${saved.id}/publish`,{method:'POST'});router.push('/dashboard/business/campaigns');}catch(e){setError(message(e));setBusy(false)}}
  const toggleCategory=(categoryId:string)=>patch({categoryIds:form.categoryIds.includes(categoryId)?form.categoryIds.filter(id=>id!==categoryId):[...form.categoryIds,categoryId].slice(0,5)});
  const togglePlatform=(platform:string)=>patch({platforms:form.platforms.some(x=>x.platform===platform)?form.platforms.filter(x=>x.platform!==platform):[...form.platforms,{platform,required:true}]});
  const addDeliverable=()=>patch({deliverables:[...form.deliverables,{title:'',description:'',quantity:1,platform:'INSTAGRAM'}]});
  return <main className="campaign-builder"><header><div><Link href="/dashboard/business/campaigns">← Campaigns</Link><p className="eyebrow">CAMPAIGN BUILDER</p><h1>{id?'Edit campaign':'Create an opportunity'}</h1></div><button className="button secondary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save draft'}</button></header><ol className="campaign-steps">{['Campaign basics','Creator requirements','Deliverables','Budget & dates','Review & publish'].map((name,index)=><li className={step===index+1?'active':''} key={name}><button onClick={()=>setStep(index+1)}><span>{index+1}</span>{name}</button></li>)}</ol>{error&&<p role="alert" className="form-error">{error}</p>}{notice&&<p role="status" className="form-success">{notice}</p>}
  {step===1&&<section className="campaign-form-panel"><h2>What are you promoting?</h2><div className="settings-grid"><label className="field">Campaign title<input required maxLength={160} value={form.title} onChange={e=>patch({title:e.target.value})}/></label><label className="field">Product or service<input value={form.productOrServiceName} onChange={e=>patch({productOrServiceName:e.target.value})}/></label><label className="field">Objective<select value={form.campaignObjective} onChange={e=>patch({campaignObjective:e.target.value})}>{objectives.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><label className="field">Location type<select value={form.locationType} onChange={e=>patch({locationType:e.target.value})}>{['LOCAL','NATIONAL','GLOBAL','REMOTE'].map(value=><option key={value}>{value}</option>)}</select></label></div><label className="field">Short description <small>{form.shortDescription.length}/350</small><textarea rows={3} maxLength={350} value={form.shortDescription} onChange={e=>patch({shortDescription:e.target.value})}/></label><label className="field">Full campaign brief <small>Locked from the public summary</small><textarea rows={7} maxLength={5000} value={form.fullDescription} onChange={e=>patch({fullDescription:e.target.value})}/></label><div className="settings-grid"><label className="field">Target audience<textarea rows={4} value={form.targetAudience} onChange={e=>patch({targetAudience:e.target.value})}/></label><label className="field">Expected outcomes<textarea rows={4} value={form.expectedOutcomes} onChange={e=>patch({expectedOutcomes:e.target.value})}/></label></div><h3>Categories</h3><div className="choice-grid">{categories.map(item=><label key={item.id}><input type="checkbox" checked={form.categoryIds.includes(item.id)} onChange={()=>toggleCategory(item.id)} disabled={!form.categoryIds.includes(item.id)&&form.categoryIds.length>=5}/>{item.name}</label>)}</div></section>}
  {step===2&&<section className="campaign-form-panel"><h2>Which Creators do you need?</h2>{!['GLOBAL','REMOTE'].includes(form.locationType)&&<div className="settings-grid"><label className="field">Creator country<select required value={form.campaignCountryCode} onChange={e=>patch({campaignCountryCode:e.target.value})}><option value="">Choose a country</option>{countryOptions.map(country=><option key={country.code} value={country.code}>{country.name} ({country.code})</option>)}</select></label>{form.locationType==='LOCAL'&&<label className="field">City<input required value={form.campaignCity} onChange={e=>patch({campaignCity:e.target.value})} placeholder="e.g. Nairobi"/></label>}</div>}<h3>Platforms</h3><div className="requirement-grid">{platforms.map(value=>{const item=form.platforms.find(x=>x.platform===value);return <article key={value}><label><input type="checkbox" checked={Boolean(item)} onChange={()=>togglePlatform(value)}/>{label(value)}</label>{item&&<label>Minimum followers<input type="number" min="0" value={item.minimumFollowers??''} onChange={e=>patch({platforms:form.platforms.map(x=>x.platform===value?{...x,minimumFollowers:e.target.value?Number(e.target.value):undefined}:x)})}/></label>}</article>})}</div><div className="settings-grid"><label className="field">Languages <small>Comma-separated codes</small><input value={form.languages.map(x=>x.languageCode).join(', ')} onChange={e=>patch({languages:e.target.value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean).map(languageCode=>({languageCode,required:true}))})}/></label><label className="check-line"><input type="checkbox" checked={form.verifiedCreatorsOnly} onChange={e=>patch({verifiedCreatorsOnly:e.target.checked})}/> Require Rivera-verified Creators</label></div></section>}
  {step===3&&<section className="campaign-form-panel"><div className="section-title"><div><h2>What should they create?</h2><p>Define concrete, scannable deliverables.</p></div><button className="button secondary" onClick={addDeliverable}>Add deliverable</button></div>{form.deliverables.map((item,index)=><article className="deliverable-editor" key={index}><div className="settings-grid"><label className="field">Title<input value={item.title} onChange={e=>patch({deliverables:form.deliverables.map((x,i)=>i===index?{...x,title:e.target.value}:x)})}/></label><label className="field">Quantity<input type="number" min="1" value={item.quantity} onChange={e=>patch({deliverables:form.deliverables.map((x,i)=>i===index?{...x,quantity:Number(e.target.value)}:x)})}/></label><label className="field">Platform<select value={item.platform} onChange={e=>patch({deliverables:form.deliverables.map((x,i)=>i===index?{...x,platform:e.target.value}:x)})}>{platforms.map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Content type<select value={item.contentTypeId??''} onChange={e=>patch({deliverables:form.deliverables.map((x,i)=>i===index?{...x,contentTypeId:e.target.value||undefined}:x)})}><option value="">Not specified</option>{contentTypes.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><label className="field">Description<textarea rows={2} value={item.description} onChange={e=>patch({deliverables:form.deliverables.map((x,i)=>i===index?{...x,description:e.target.value}:x)})}/></label><div className="row-actions"><button onClick={()=>patch({deliverables:form.deliverables.filter((_,i)=>i!==index)})}>Delete</button>{index>0&&<button onClick={()=>{const items=[...form.deliverables];[items[index-1],items[index]]=[items[index],items[index-1]];patch({deliverables:items})}}>Move up</button>}</div></article>)}{!form.deliverables.length&&<div className="dashboard-empty"><h3>No deliverables yet</h3><p>Add at least one before publishing.</p></div>}<div className="settings-grid"><label className="field">Usage rights<select value={form.usageRights} onChange={e=>patch({usageRights:e.target.value})}>{['ORGANIC_ONLY','PAID_ADS','BUSINESS_WEBSITE','SOCIAL_MEDIA','FULL_COMMERCIAL','TO_BE_DISCUSSED'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field">Special instructions<textarea rows={4} value={form.specialInstructions} onChange={e=>patch({specialInstructions:e.target.value})}/></label><label className="check-line"><input type="checkbox" checked={form.productProvided} onChange={e=>patch({productProvided:e.target.checked})}/> Product will be supplied</label><label className="check-line"><input type="checkbox" checked={form.travelExpensesCovered} onChange={e=>patch({travelExpensesCovered:e.target.checked})}/> Travel expenses covered</label></div></section>}
  {step===4&&<section className="campaign-form-panel"><h2>Budget and timeline</h2><div className="settings-grid"><label className="field">Currency<input maxLength={3} value={form.currencyCode} onChange={e=>patch({currencyCode:e.target.value.toUpperCase()})}/></label><label className="field">Minimum budget<input type="number" min="0" value={form.budgetMinMinor==null?'':form.budgetMinMinor/100} onChange={e=>patch({budgetMinMinor:e.target.value?Math.round(Number(e.target.value)*100):undefined})}/></label><label className="field">Maximum budget<input type="number" min="0" value={form.budgetMaxMinor==null?'':form.budgetMaxMinor/100} onChange={e=>patch({budgetMaxMinor:e.target.value?Math.round(Number(e.target.value)*100):undefined})}/></label><label className="field">Budget visibility<select value={form.budgetVisibility} onChange={e=>patch({budgetVisibility:e.target.value})}><option>PUBLIC</option><option>HIDDEN</option></select></label><label className="field">Creator slots<input type="number" min="1" value={form.creatorSlots} onChange={e=>patch({creatorSlots:Number(e.target.value)})}/></label><label className="field">Application deadline<input type="date" value={form.applicationDeadline} onChange={e=>patch({applicationDeadline:e.target.value})}/></label><label className="field">Campaign start<input type="date" value={form.campaignStartDate} onChange={e=>patch({campaignStartDate:e.target.value})}/></label><label className="field">Campaign end<input type="date" value={form.campaignEndDate} onChange={e=>patch({campaignEndDate:e.target.value})}/></label></div></section>}
  {step===5&&<section className="campaign-form-panel campaign-review"><h2>Review your opportunity</h2><article><p className="eyebrow">CAMPAIGN</p><h3>{form.title||'Untitled campaign'}</h3><p>{form.shortDescription||'Add a short description.'}</p></article><article><p className="eyebrow">CREATOR REQUIREMENTS</p><p>{label(form.locationType)} · {form.platforms.map(x=>label(x.platform)).join(', ')||'No platforms'} · {form.languages.map(x=>x.languageCode.toUpperCase()).join(', ')}</p></article><article><p className="eyebrow">DELIVERABLES</p>{form.deliverables.map((x,i)=><p key={i}>{x.quantity} × {x.title||'Untitled deliverable'}</p>)}</article><article><p className="eyebrow">BUDGET & TIMELINE</p><p>{form.budgetVisibility==='HIDDEN'?'Budget to be discussed':`${form.currencyCode} ${((form.budgetMinMinor??0)/100).toLocaleString()} – ${((form.budgetMaxMinor??form.budgetMinMinor??0)/100).toLocaleString()}`} · closes {form.applicationDeadline||'flexible'}</p></article><p className="privacy-note">Creators see only the public summary. Your full description, target audience, expected outcomes and special instructions remain locked for a later authorized application workflow.</p><div className="dashboard-actions"><button className="button secondary" disabled={busy} onClick={()=>void save()}>Save draft</button><button className="button primary" disabled={busy} onClick={()=>void publish()}>Publish campaign</button></div></section>}
  <footer className="wizard-footer">{step>1&&<button className="button secondary" onClick={()=>setStep(value=>value-1)}>Back</button>}{step<5&&<button className="button primary" onClick={()=>void next()}>Save and continue</button>}</footer></main>;
}

export function BusinessCampaigns(){const [result,setResult]=useState<{items:Campaign[]}|null>(null),[filter,setFilter]=useState(''),[error,setError]=useState('');const load=()=>api<{items:Campaign[]}>(`/business/campaigns${filter?`?status=${filter}`:''}`).then(setResult).catch(e=>setError(message(e)));useEffect(()=>{void load()},[filter]);async function act(id:string,action:string){try{await api(`/business/campaigns/${id}/${action}`,{method:'POST'});load()}catch(e){setError(message(e))}}async function remove(id:string){try{await api(`/business/campaigns/${id}`,{method:'DELETE'});load()}catch(e){setError(message(e))}}return <main className="campaign-dashboard"><header><div><Link href="/dashboard/business">← Dashboard</Link><p className="eyebrow">BUSINESS CAMPAIGNS</p><h1>Campaigns</h1></div><Link className="button primary" href="/dashboard/business/campaigns/new">Create campaign</Link></header><label className="field status-filter">Status<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All</option>{['DRAFT','PENDING_REVIEW','OPEN','PAUSED','CLOSED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></label>{error&&<p className="form-error">{error}</p>}{result?.items.length?<div className="campaign-list">{result.items.map(c=><article className="owner-campaign" key={c.id}><div><p className="eyebrow">{c.status} · {c.visibility}</p><h2>{c.title}</h2><p>{c.shortDescription||'Draft description not added yet.'}</p><div className="campaign-facts"><span>{location(c)}</span><span>{budget(c)}</span><span>{c.viewCount??0} views</span><span>{deadline(c.applicationDeadline)}</span></div></div><div className="owner-actions"><Link href={`/dashboard/business/campaigns/${c.id}`}>Manage</Link><Link href={`/dashboard/business/campaigns/${c.id}/edit`}>Edit</Link>{c.status==='DRAFT'&&<><button onClick={()=>void act(c.id,'publish')}>Publish</button><button onClick={()=>void remove(c.id)}>Delete draft</button></>}{c.status==='OPEN'&&<button onClick={()=>void act(c.id,'pause')}>Pause</button>}{c.status==='PAUSED'&&<button onClick={()=>void act(c.id,'resume')}>Resume</button>}{['OPEN','PAUSED'].includes(c.status)&&<button onClick={()=>void act(c.id,'close')}>Close</button>}<button onClick={()=>void act(c.id,'duplicate')}>Duplicate</button></div></article>)}</div>:<div className="dashboard-empty"><h2>Create your first campaign.</h2><p>Describe the opportunity, define the Creators you need and publish it to Rivera.</p></div>}</main>}

export function BusinessCampaignDetail({id}:{id:string}){const [campaign,setCampaign]=useState<Campaign|null>(null),[error,setError]=useState('');useEffect(()=>{api<Campaign>(`/business/campaigns/${id}`).then(setCampaign).catch(e=>setError(message(e)))},[id]);if(error)return <p className="form-error">{error}</p>;if(!campaign)return <p>Loading campaign…</p>;return <main className="campaign-detail owner-brief"><header><Link href="/dashboard/business/campaigns">← Campaigns</Link><p className="eyebrow">{campaign.status} · OWNER FULL BRIEF</p><h1>{campaign.title}</h1><p>{campaign.applicationsCount ?? 0} application{campaign.applicationsCount===1?'':'s'}</p><div className="dashboard-actions"><Link className="button primary" href={`/dashboard/business/campaigns/${id}/applications`}>View Applications</Link><Link className="button secondary" href={`/dashboard/business/campaigns/${id}/creators`}>Hired Creators</Link><Link className="button secondary" href={`/dashboard/business/campaigns/${id}/edit`}>Edit campaign</Link>{campaign.status==='OPEN'&&<Link className="button secondary" href={`/campaigns/${campaign.slug}`}>Public preview</Link>}</div></header><section><h2>Public summary</h2><p>{campaign.shortDescription}</p><div className="campaign-facts"><span>{location(campaign)}</span><span>{budget(campaign)}</span><span>{label(campaign.campaignObjective)}</span></div></section><section className="locked-brief"><p className="eyebrow">LOCKED BRIEF</p><h2>Full description</h2><p>{campaign.fullDescription}</p><h3>Target audience</h3><p>{campaign.targetAudience||'Not specified'}</p><h3>Expected outcomes</h3><p>{campaign.expectedOutcomes||'Not specified'}</p><h3>Special instructions</h3><p>{campaign.specialInstructions||'None'}</p></section><section><h2>Deliverables</h2>{campaign.deliverables.map((x,i)=><article key={x.id??i}><strong>{x.quantity} × {x.title}</strong><p>{x.description}</p></article>)}</section></main>}

function message(error:unknown){return error instanceof ApiError?error.message:'Something went wrong. Please try again.'}
