'use client';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { HeartHandshake } from 'lucide-react';
import { api } from '@/lib/api';

type Pending = { email:string; firstName:string; lastName:string; profileImageUrl:string|null };
export function GoogleRegistrationForm() {
  const search = useSearchParams()!;
  const token = search.get('token') ?? '';
  const [pending,setPending] = useState<Pending|null>(null);
  const [firstName,setFirstName] = useState(''); const [lastName,setLastName] = useState('');
  const [accountType,setAccountType] = useState<'BUSINESS'|'CREATOR'>('CREATOR'); const [terms,setTerms] = useState(false);
  const [error,setError] = useState(''); const [message,setMessage] = useState(''); const [busy,setBusy] = useState(false);
  useEffect(()=>{ if(!token){setError('This Google registration link is missing. Please start again.');return;} void api<Pending>(`/auth/google/pending?token=${encodeURIComponent(token)}`,{},false).then(value=>{setPending(value);setFirstName(value.firstName);setLastName(value.lastName)}).catch(e=>setError(e instanceof Error?e.message:'Please start Google sign-in again.')); },[token]);
  async function submit(event:React.FormEvent){event.preventDefault();setError('');setBusy(true);try{const result=await api<{message:string}>('/auth/google/register',{method:'POST',body:JSON.stringify({token,firstName,lastName,accountType,termsAccepted:terms})},false);setMessage(result.message)}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
  return <main className="auth-shell"><div className="auth-frame"><section className="auth-story"><Link href="/" className="brand"><span className="brand-mark">R.</span>rivera</Link><div className="auth-story-copy"><span className="auth-story-icon"><HeartHandshake size={25}/></span><p className="eyebrow">GOOGLE, THEN RIVERA</p><h2>Bring your identity. Choose your path.</h2><p>Google confirms who you are. You decide how you want to create, collaborate and grow on Rivera.</p></div></section><section className="auth-form-side"><Link href="/register" className="auth-back">← Other sign-up options</Link><div className="auth-card"><p className="eyebrow">COMPLETE YOUR ACCOUNT</p><h1>Make Rivera yours</h1><p className="auth-intro">Review your name, choose your account type, then activate your account from the email we send.</p>{pending && !message&&<form onSubmit={submit}><div className="google-identity">{pending.profileImageUrl?<img src={pending.profileImageUrl} alt="" referrerPolicy="no-referrer"/>:<span>{firstName.slice(0,1)}{lastName.slice(0,1)}</span>}<div><strong>{pending.email}</strong><small>Verified by Google</small></div></div><label className="field"><span>First name</span><input value={firstName} onChange={e=>setFirstName(e.target.value)} required maxLength={80}/></label><label className="field"><span>Last name</span><input value={lastName} onChange={e=>setLastName(e.target.value)} required maxLength={80}/></label><fieldset className="roles"><legend>I am joining as</legend><label><input type="radio" checked={accountType==='BUSINESS'} onChange={()=>setAccountType('BUSINESS')}/> A business</label><label><input type="radio" checked={accountType==='CREATOR'} onChange={()=>setAccountType('CREATOR')}/> A content creator</label></fieldset><label className="terms-check"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)} required/><span>I agree to Rivera’s <Link href="/terms">Terms of Service</Link> and <Link href="/privacy">Privacy Policy</Link>.</span></label><button className="button primary form-submit" disabled={busy}>{busy?'Creating account…':'Create account & send activation'}</button></form>}{error&&<p className="form-error" role="alert">{error}</p>}{message&&<><p className="form-success" role="status">{message}</p><Link className="button primary" href="/login">Continue to login</Link></>}</div></section></div></main>;
}
