CREATE TYPE "PayoutAccountStatus" AS ENUM ('NOT_STARTED','PENDING','RESTRICTED','ACTIVE','DISABLED');
CREATE TYPE "CollaborationPaymentStatus" AS ENUM ('NOT_FUNDED','PAYMENT_PENDING','FUNDED','PARTIALLY_REFUNDED','REFUNDED','RELEASE_PENDING','RELEASED','PAYOUT_PENDING','SETTLED','FAILED','CANCELLED');
CREATE TYPE "CreatorTransferStatus" AS ENUM ('PENDING','SUCCEEDED','FAILED','REVERSED');
CREATE TYPE "PaymentIssueType" AS ENUM ('PAYMENT_NOT_RELEASED','WORK_NOT_COMPLETED','UNAUTHORIZED_CHARGE','REFUND_REQUEST','CREATOR_PAYOUT_PROBLEM','PROVIDER_DISPUTE','OTHER');
CREATE TYPE "PaymentIssueStatus" AS ENUM ('OPEN','UNDER_REVIEW','RESOLVED','CLOSED');

CREATE TABLE "CreatorPayoutAccount" ("id" TEXT PRIMARY KEY,"creatorId" TEXT NOT NULL UNIQUE,"provider" "PaymentProvider" NOT NULL DEFAULT 'STRIPE',"providerAccountId" TEXT NOT NULL UNIQUE,"countryCode" VARCHAR(2) NOT NULL,"defaultCurrencyCode" VARCHAR(3),"onboardingStatus" "PayoutAccountStatus" NOT NULL DEFAULT 'PENDING',"chargesEnabled" BOOLEAN NOT NULL DEFAULT false,"payoutsEnabled" BOOLEAN NOT NULL DEFAULT false,"detailsSubmitted" BOOLEAN NOT NULL DEFAULT false,"requirementsDueJson" JSONB,"lastSyncedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CollaborationPayment" ("id" TEXT PRIMARY KEY,"campaignParticipantId" TEXT NOT NULL UNIQUE,"campaignId" TEXT NOT NULL,"businessId" TEXT NOT NULL,"creatorId" TEXT NOT NULL,"provider" "PaymentProvider" NOT NULL DEFAULT 'STRIPE',"providerPaymentIntentId" TEXT UNIQUE,"providerCheckoutSessionId" TEXT UNIQUE,"providerChargeId" TEXT UNIQUE,"grossAmountMinor" INTEGER NOT NULL,"currencyCode" VARCHAR(3) NOT NULL,"platformFeeMinor" INTEGER NOT NULL,"providerFeeMinor" INTEGER,"creatorNetMinor" INTEGER NOT NULL,"fundedAmountMinor" INTEGER NOT NULL DEFAULT 0,"refundedAmountMinor" INTEGER NOT NULL DEFAULT 0,"releasedAmountMinor" INTEGER NOT NULL DEFAULT 0,"status" "CollaborationPaymentStatus" NOT NULL DEFAULT 'NOT_FUNDED',"fundedAt" TIMESTAMP(3),"eligibleForReleaseAt" TIMESTAMP(3),"releasedAt" TIMESTAMP(3),"settledAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CollaborationPayment_amounts_check" CHECK ("grossAmountMinor">=0 AND "platformFeeMinor">=0 AND "creatorNetMinor">=0 AND "fundedAmountMinor">=0 AND "refundedAmountMinor">=0 AND "releasedAmountMinor">=0));
CREATE TABLE "CreatorTransfer" ("id" TEXT PRIMARY KEY,"collaborationPaymentId" TEXT NOT NULL,"creatorId" TEXT NOT NULL,"provider" "PaymentProvider" NOT NULL DEFAULT 'STRIPE',"providerTransferId" TEXT NOT NULL UNIQUE,"amountMinor" INTEGER NOT NULL,"currencyCode" VARCHAR(3) NOT NULL,"status" "CreatorTransferStatus" NOT NULL DEFAULT 'PENDING',"failureCode" VARCHAR(100),"failureMessage" VARCHAR(500),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"releasedAt" TIMESTAMP(3),"settledAt" TIMESTAMP(3),CONSTRAINT "CreatorTransfer_amount_check" CHECK ("amountMinor">0),CONSTRAINT "CreatorTransfer_payment_amount_key" UNIQUE ("collaborationPaymentId","amountMinor"));
CREATE TABLE "CollaborationRefund" ("id" TEXT PRIMARY KEY,"collaborationPaymentId" TEXT NOT NULL,"providerRefundId" TEXT UNIQUE,"amountMinor" INTEGER NOT NULL,"currencyCode" VARCHAR(3) NOT NULL,"reason" VARCHAR(500) NOT NULL,"status" "PaymentRefundStatus" NOT NULL DEFAULT 'PENDING',"requestedByUserId" TEXT,"approvedByAdminId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),CONSTRAINT "CollaborationRefund_amount_check" CHECK ("amountMinor">0));
CREATE TABLE "PaymentIssue" ("id" TEXT PRIMARY KEY,"campaignParticipantId" TEXT NOT NULL,"collaborationPaymentId" TEXT,"openedByUserId" TEXT NOT NULL,"type" "PaymentIssueType" NOT NULL,"description" VARCHAR(2000) NOT NULL,"status" "PaymentIssueStatus" NOT NULL DEFAULT 'OPEN',"providerDisputeId" TEXT UNIQUE,"adminNote" VARCHAR(2000),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"resolvedAt" TIMESTAMP(3));
CREATE TABLE "PlatformSetting" ("key" VARCHAR(100) PRIMARY KEY,"value" VARCHAR(500) NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);

CREATE INDEX "CreatorPayoutAccount_onboardingStatus_idx" ON "CreatorPayoutAccount"("onboardingStatus");
CREATE INDEX "CollaborationPayment_businessId_status_idx" ON "CollaborationPayment"("businessId","status");
CREATE INDEX "CollaborationPayment_creatorId_status_idx" ON "CollaborationPayment"("creatorId","status");
CREATE INDEX "CollaborationPayment_campaignId_idx" ON "CollaborationPayment"("campaignId");
CREATE INDEX "CollaborationPayment_status_updatedAt_idx" ON "CollaborationPayment"("status","updatedAt");
CREATE INDEX "CreatorTransfer_creatorId_status_idx" ON "CreatorTransfer"("creatorId","status");
CREATE INDEX "CollaborationRefund_collaborationPaymentId_status_idx" ON "CollaborationRefund"("collaborationPaymentId","status");
CREATE INDEX "PaymentIssue_status_createdAt_idx" ON "PaymentIssue"("status","createdAt");
CREATE INDEX "PaymentIssue_campaignParticipantId_idx" ON "PaymentIssue"("campaignParticipantId");

ALTER TABLE "CreatorPayoutAccount" ADD CONSTRAINT "CreatorPayoutAccount_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "CreatorProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationPayment" ADD CONSTRAINT "CollaborationPayment_campaignParticipantId_fkey" FOREIGN KEY ("campaignParticipantId") REFERENCES "CampaignParticipant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationPayment" ADD CONSTRAINT "CollaborationPayment_campaignId_fkey" FOREIGN KEY ("campaignId") REFERENCES "Campaign"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationPayment" ADD CONSTRAINT "CollaborationPayment_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "BusinessProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationPayment" ADD CONSTRAINT "CollaborationPayment_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "CreatorProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CreatorTransfer" ADD CONSTRAINT "CreatorTransfer_collaborationPaymentId_fkey" FOREIGN KEY ("collaborationPaymentId") REFERENCES "CollaborationPayment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CreatorTransfer" ADD CONSTRAINT "CreatorTransfer_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "CreatorProfile"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationRefund" ADD CONSTRAINT "CollaborationRefund_collaborationPaymentId_fkey" FOREIGN KEY ("collaborationPaymentId") REFERENCES "CollaborationPayment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CollaborationRefund" ADD CONSTRAINT "CollaborationRefund_requestedByUserId_fkey" FOREIGN KEY ("requestedByUserId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "CollaborationRefund" ADD CONSTRAINT "CollaborationRefund_approvedByAdminId_fkey" FOREIGN KEY ("approvedByAdminId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "PaymentIssue" ADD CONSTRAINT "PaymentIssue_campaignParticipantId_fkey" FOREIGN KEY ("campaignParticipantId") REFERENCES "CampaignParticipant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentIssue" ADD CONSTRAINT "PaymentIssue_collaborationPaymentId_fkey" FOREIGN KEY ("collaborationPaymentId") REFERENCES "CollaborationPayment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentIssue" ADD CONSTRAINT "PaymentIssue_openedByUserId_fkey" FOREIGN KEY ("openedByUserId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
