import assert from 'node:assert/strict'; import { readFileSync } from 'node:fs'; import test from 'node:test';
const source=(p:string)=>readFileSync(new URL(p,import.meta.url),'utf8');
const service=source('../src/payments/marketplace-payment.service.ts'),provider=source('../src/applications/payment.provider.ts'),schema=source('../prisma/schema.prisma'),controllers=source('../src/payments/marketplace-payment.controllers.ts'),webhook=source('../src/applications/applications.service.ts');
test('Phase 5 application fees remain a separate payment model',()=>{assert.match(schema,/model ApplicationPayment/);assert.match(schema,/model CollaborationPayment/);});
test('Business payment ownership and Creator earnings are IDOR protected',()=>{assert.match(service,/business: \{ userId \}/);assert.match(service,/creator: \{ userId \}/);assert.match(controllers,/@Roles\("?BUSINESS"?\)|@Roles\('BUSINESS'\)/);});
test('frontend cannot provide authoritative funding amounts',()=>{assert.match(service,/agreedCompensationMinor/);assert.doesNotMatch(controllers,/amountMinor.*fund/);});
test('marketplace fee is integer calculated and snapshotted',()=>{assert.match(service,/Math\.floor/);assert.match(schema,/platformFeeMinor/);assert.match(schema,/creatorNetMinor/);});
test('funding is webhook confirmed with amount and currency checks',()=>{assert.match(service,/PAYMENT_AMOUNT_MISMATCH/);assert.match(service,/PAYMENT_CURRENCY_MISMATCH/);assert.match(service,/status: "FUNDED"/);});
test('webhook events stay globally idempotent',()=>{assert.match(webhook,/provider_providerEventId/);assert.match(webhook,/duplicate: true/);});
test('release requires funded completed approved work and payout readiness',()=>{assert.match(service,/PAYMENT_NOT_FUNDED/);assert.match(service,/p\.status === "COMPLETED"/);assert.match(service,/x\.status === "APPROVED"/);assert.match(service,/PAYOUT_ACCOUNT_UNAVAILABLE/);});
test('release uses provider idempotency and database serialization',()=>{assert.match(service,/pg_advisory_xact_lock/);assert.match(service,/rivera-release-/);assert.match(schema,/providerTransferId.*@unique/);});
test('refund state changes only after provider response',()=>{assert.match(service,/provider\.refund/);assert.match(service,/PROVIDER_REFUND_FAILED/);assert.match(service,/refundedAmountMinor/);});
test('pending and duplicate refunds remain provider-controlled',()=>{assert.match(service,/REFUND_ALREADY_PENDING/);assert.match(service,/refund\.updated/);assert.match(service,/completeRefund/);});
test('connected account state is provider authoritative',()=>{assert.match(provider,/retrieveConnectedAccount/);assert.match(service,/account\.updated/);assert.match(service,/payoutsEnabled: connected\.payoutsEnabled/);});
test('disputes are recorded as payment issues',()=>{assert.match(service,/charge\.dispute/);assert.match(service,/PROVIDER_DISPUTE/);});
test('multi-currency reporting groups totals by currency',()=>{assert.match(service,/a\[x\.currencyCode\]/);});
test('financial models never contain raw card or bank fields',()=>{for(const term of ['cardNumber','cvv','bankAccountNumber','secretKey'])assert.doesNotMatch(schema,new RegExp(term,'i'));});
test('money moving endpoints have rate limits',()=>{assert.match(controllers,/campaign-participants\/:id\/payment[\s\S]*@Throttle/);assert.match(controllers,/collaboration-payments\/:id\/release[\s\S]*@Throttle/);assert.match(controllers,/collaboration-payments\/:id\/refund[\s\S]*@Throttle/);});
test('reconciliation covers payment refunds transfers and payout accounts',()=>{assert.match(service,/async reconcile/);assert.match(service,/retrievePayment/);assert.match(service,/retrieveRefund/);assert.match(service,/retrieveTransfer/);assert.match(service,/reconcilePayoutAccount/);});
